// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("AbilityTemplate", {
  id: __t.u64(),
  key: __t.string(),
  name: __t.string(),
  className: __t.string(),
  level: __t.u64(),
  resource: __t.string(),
  castSeconds: __t.u64(),
  cooldownSeconds: __t.u64(),
  kind: __t.string(),
  combatState: __t.string(),
  description: __t.string(),
  power: __t.option(__t.u64()),
  damageType: __t.option(__t.string()),
  statScaling: __t.option(__t.string()),
  dotPowerSplit: __t.option(__t.f64()),
  dotDuration: __t.option(__t.u64()),
  hotPowerSplit: __t.option(__t.f64()),
  hotDuration: __t.option(__t.u64()),
  debuffType: __t.option(__t.string()),
  debuffMagnitude: __t.option(__t.i64()),
  debuffDuration: __t.option(__t.u64()),
  aoeTargets: __t.option(__t.string()),
});


