// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  name: __t.string(),
  className: __t.string().name("class_name"),
  level: __t.u64(),
  resource: __t.string(),
  castSeconds: __t.u64().name("cast_seconds"),
  cooldownSeconds: __t.u64().name("cooldown_seconds"),
  kind: __t.string(),
  combatState: __t.string().name("combat_state"),
  description: __t.string(),
  power: __t.option(__t.u64()),
  damageType: __t.option(__t.string()).name("damage_type"),
  statScaling: __t.option(__t.string()).name("stat_scaling"),
  dotPowerSplit: __t.option(__t.f64()).name("dot_power_split"),
  dotDuration: __t.option(__t.u64()).name("dot_duration"),
  hotPowerSplit: __t.option(__t.f64()).name("hot_power_split"),
  hotDuration: __t.option(__t.u64()).name("hot_duration"),
  debuffType: __t.option(__t.string()).name("debuff_type"),
  debuffMagnitude: __t.option(__t.i64()).name("debuff_magnitude"),
  debuffDuration: __t.option(__t.u64()).name("debuff_duration"),
  aoeTargets: __t.option(__t.string()).name("aoe_targets"),
  resourceCost: __t.u64().name("resource_cost"),
});
