// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  combatId: __t.option(__t.u64()).name("combat_id"),
  name: __t.string(),
  level: __t.u64(),
  currentHp: __t.u64().name("current_hp"),
  maxHp: __t.u64().name("max_hp"),
  attackDamage: __t.u64().name("attack_damage"),
  abilityKey: __t.option(__t.string()).name("ability_key"),
  nextAbilityAt: __t.option(__t.u64()).name("next_ability_at"),
  abilityCooldownSeconds: __t.option(__t.u64()).name("ability_cooldown_seconds"),
  targetEnemyId: __t.option(__t.u64()).name("target_enemy_id"),
  nextAutoAttackAt: __t.option(__t.u64()).name("next_auto_attack_at"),
  expiresAtMicros: __t.option(__t.u64()).name("expires_at_micros"),
});
