// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  bardCharacterId: __t.u64().name("bard_character_id"),
  combatId: __t.option(__t.u64()).name("combat_id"),
  songKey: __t.string().name("song_key"),
  startedAtMicros: __t.u64().name("started_at_micros"),
  isFading: __t.bool().name("is_fading"),
});
