// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64(),
  combatId: __t.option(__t.u64()),
  name: __t.string(),
  level: __t.u64(),
  currentHp: __t.u64(),
  maxHp: __t.u64(),
  attackDamage: __t.u64(),
  abilityKey: __t.option(__t.string()),
  nextAbilityAt: __t.option(__t.u64()),
  abilityCooldownSeconds: __t.option(__t.u64()),
  targetEnemyId: __t.option(__t.u64()),
  nextAutoAttackAt: __t.option(__t.u64()),
  expiresAtMicros: __t.option(__t.u64()),
});
