// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  keySet: __t.bool().name("key_set"),
  keyLength: __t.u64().name("key_length"),
  keyValid: __t.bool().name("key_valid"),
  keyUpdatedAt: __t.option(__t.timestamp()).name("key_updated_at"),
  keyVerifiedAt: __t.option(__t.timestamp()).name("key_verified_at"),
  lastSmokeAt: __t.option(__t.timestamp()).name("last_smoke_at"),
  lastSmokeJson: __t.string().name("last_smoke_json"),
  phaseSpentMicroUsd: __t.u64().name("phase_spent_micro_usd"),
  phaseReservedMicroUsd: __t.u64().name("phase_reserved_micro_usd"),
  phaseCalls: __t.u64().name("phase_calls"),
  dailyCeilingMicroUsd: __t.u64().name("daily_ceiling_micro_usd"),
  llmEnabled: __t.bool().name("llm_enabled"),
  spendDayUtc: __t.string().name("spend_day_utc"),
  daySpentMicroUsd: __t.u64().name("day_spent_micro_usd"),
  inFlight: __t.u64().name("in_flight"),
});
