// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("AggroEntry", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyId: __t.u64(),
  characterId: __t.u64(),
  petId: __t.option(__t.u64()),
  value: __t.u64(),
});


