// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerUserId: __t.u64(),
  name: __t.string(),
  race: __t.string(),
  className: __t.string(),
  level: __t.u64(),
  xp: __t.u64(),
  locationId: __t.u64(),
  groupId: __t.option(__t.u64()),
  hp: __t.u64(),
  maxHp: __t.u64(),
  mana: __t.u64(),
  maxMana: __t.u64(),
  str: __t.u64(),
  dex: __t.u64(),
  cha: __t.u64(),
  wis: __t.u64(),
  int: __t.u64(),
  hitChance: __t.u64(),
  dodgeChance: __t.u64(),
  parryChance: __t.u64(),
  critMelee: __t.u64(),
  critRanged: __t.u64(),
  critDivine: __t.u64(),
  critArcane: __t.u64(),
  perception: __t.u64(),
  search: __t.u64(),
  ccPower: __t.u64(),
  vendorBuyMod: __t.u64(),
  vendorSellMod: __t.u64(),
  createdAt: __t.timestamp(),
  stamina: __t.u64(),
  maxStamina: __t.u64(),
});
