// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Character", {
  id: __t.u64(),
  ownerId: __t.identity(),
  name: __t.string(),
  race: __t.string(),
  className: __t.string(),
  level: __t.u64(),
  xp: __t.u64(),
  locationId: __t.u64(),
  hp: __t.u64(),
  maxHp: __t.u64(),
  mana: __t.u64(),
  maxMana: __t.u64(),
  createdAt: __t.timestamp(),
});


