// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64().name("combat_id"),
  enemyTemplateId: __t.u64().name("enemy_template_id"),
  enemyRoleTemplateId: __t.option(__t.u64()).name("enemy_role_template_id"),
  spawnId: __t.option(__t.u64()).name("spawn_id"),
  arriveAtMicros: __t.u64().name("arrive_at_micros"),
});
