// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64().name("combat_id"),
  enemyId: __t.u64().name("enemy_id"),
  abilityKey: __t.string().name("ability_key"),
  endsAtMicros: __t.u64().name("ends_at_micros"),
  targetCharacterId: __t.option(__t.u64()).name("target_character_id"),
  targetPetId: __t.option(__t.u64()).name("target_pet_id"),
});
