// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  locationId: __t.u64().name("location_id"),
  groupId: __t.option(__t.u64()).name("group_id"),
  leaderCharacterId: __t.option(__t.u64()).name("leader_character_id"),
  state: __t.string(),
  addCount: __t.u64().name("add_count"),
  pendingAddCount: __t.u64().name("pending_add_count"),
  pendingAddAtMicros: __t.option(__t.u64()).name("pending_add_at_micros"),
  createdAt: __t.timestamp().name("created_at"),
});
