// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64(),
  ownerUserId: __t.u64(),
  characterId: __t.u64(),
  itemTemplateId: __t.u64(),
  createdAt: __t.timestamp(),
  qualityTier: __t.option(__t.string()),
  affixDataJson: __t.option(__t.string()),
  isNamed: __t.option(__t.bool()),
  craftQuality: __t.option(__t.string()),
});
