// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64().name("combat_id"),
  enemyId: __t.u64().name("enemy_id"),
  effectType: __t.string().name("effect_type"),
  magnitude: __t.i64(),
  roundsRemaining: __t.u64().name("rounds_remaining"),
  sourceAbility: __t.option(__t.string()).name("source_ability"),
  ownerCharacterId: __t.option(__t.u64()).name("owner_character_id"),
});
