// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("CombatPet", {
  id: __t.u64(),
  combatId: __t.u64(),
  ownerCharacterId: __t.u64(),
  name: __t.string(),
  currentHp: __t.u64(),
  maxHp: __t.u64(),
  attackDamage: __t.u64(),
  targetEnemyId: __t.option(__t.u64()),
  nextAutoAttackAt: __t.u64(),
});


