// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64(),
  enemyTemplateId: __t.u64(),
  currentHp: __t.u64(),
  maxHp: __t.u64(),
  attackDamage: __t.u64(),
  armorClass: __t.u64(),
  aggroTargetCharacterId: __t.option(__t.u64()),
});
