// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("CombatEnemyEffect", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyId: __t.u64(),
  effectType: __t.string(),
  magnitude: __t.i64(),
  roundsRemaining: __t.u64(),
  sourceAbility: __t.option(__t.string()),
  ownerCharacterId: __t.option(__t.u64()),
});


