// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Combat", {
  id: __t.u64(),
  characterId: __t.u64(),
  enemyId: __t.u64(),
  enemyName: __t.string(),
  enemyLevel: __t.u64(),
  enemyHp: __t.u64(),
  enemyMaxHp: __t.u64(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});


