// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  characterId: __t.u64(),
  recipeTemplateId: __t.u64(),
  catalystTemplateId: __t.option(__t.u64()),
  modifier1TemplateId: __t.option(__t.u64()),
  modifier2TemplateId: __t.option(__t.u64()),
  modifier3TemplateId: __t.option(__t.u64()),
};
