// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("EnemyTemplate", {
  id: __t.u64(),
  name: __t.string(),
  role: __t.string(),
  roleDetail: __t.string(),
  abilityProfile: __t.string(),
  terrainTypes: __t.string(),
  creatureType: __t.string(),
  timeOfDay: __t.string(),
  socialGroup: __t.string(),
  socialRadius: __t.u64(),
  awareness: __t.string(),
  groupMin: __t.u64(),
  groupMax: __t.u64(),
  armorClass: __t.u64(),
  level: __t.u64(),
  maxHp: __t.u64(),
  baseDamage: __t.u64(),
  xpReward: __t.u64(),
});


