// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("EventObjective", {
  id: __t.u64(),
  eventId: __t.u64(),
  objectiveType: __t.string(),
  locationId: __t.u64(),
  name: __t.string(),
  targetCount: __t.u64(),
  currentCount: __t.u64(),
  isAlive: __t.option(__t.bool()),
});


