// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Hunger", {
  id: __t.u64(),
  characterId: __t.u64(),
  currentHunger: __t.u64(),
  wellFedUntil: __t.timestamp(),
  wellFedBuffType: __t.string(),
  wellFedBuffMagnitude: __t.u64(),
});


