// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import SetAppVersionReducer from "./set_app_version_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SendFriendRequestToCharacterReducer from "./send_friend_request_to_character_reducer";
import AcceptFriendRequestReducer from "./accept_friend_request_reducer";
import RejectFriendRequestReducer from "./reject_friend_request_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import LoginEmailReducer from "./login_email_reducer";
import LogoutReducer from "./logout_reducer";
import SetActiveCharacterReducer from "./set_active_character_reducer";
import ClearActiveCharacterReducer from "./clear_active_character_reducer";
import CreateCharacterReducer from "./create_character_reducer";
import BindLocationReducer from "./bind_location_reducer";
import DeleteCharacterReducer from "./delete_character_reducer";
import RespawnCharacterReducer from "./respawn_character_reducer";
import CreateItemTemplateReducer from "./create_item_template_reducer";
import GrantItemReducer from "./grant_item_reducer";
import BuyItemReducer from "./buy_item_reducer";
import SellItemReducer from "./sell_item_reducer";
import SellAllJunkReducer from "./sell_all_junk_reducer";
import TakeLootReducer from "./take_loot_reducer";
import TakeAllLootReducer from "./take_all_loot_reducer";
import EquipItemReducer from "./equip_item_reducer";
import UnequipItemReducer from "./unequip_item_reducer";
import DeleteItemReducer from "./delete_item_reducer";
import SplitStackReducer from "./split_stack_reducer";
import ConsolidateStacksReducer from "./consolidate_stacks_reducer";
import SetHotbarSlotReducer from "./set_hotbar_slot_reducer";
import UseAbilityReducer from "./use_ability_reducer";
import UseItemReducer from "./use_item_reducer";
import SyncEquipmentTablesReducer from "./sync_equipment_tables_reducer";
import SyncLootTablesReducer from "./sync_loot_tables_reducer";
import SyncEnemyContentReducer from "./sync_enemy_content_reducer";
import SyncWorldLayoutReducer from "./sync_world_layout_reducer";
import SyncAbilityTemplatesReducer from "./sync_ability_templates_reducer";
import SyncRecipeTemplatesReducer from "./sync_recipe_templates_reducer";
import SyncNpcQuestContentReducer from "./sync_npc_quest_content_reducer";
import SyncAllContentReducer from "./sync_all_content_reducer";
import ResearchRecipesReducer from "./research_recipes_reducer";
import CraftRecipeReducer from "./craft_recipe_reducer";
import LearnRecipeScrollReducer from "./learn_recipe_scroll_reducer";
import SalvageItemReducer from "./salvage_item_reducer";
import StartGatherResourceReducer from "./start_gather_resource_reducer";
import StartTradeReducer from "./start_trade_reducer";
import AddTradeItemReducer from "./add_trade_item_reducer";
import RemoveTradeItemReducer from "./remove_trade_item_reducer";
import OfferTradeReducer from "./offer_trade_reducer";
import CancelTradeReducer from "./cancel_trade_reducer";
import MoveCharacterReducer from "./move_character_reducer";
import SubmitCommandReducer from "./submit_command_reducer";
import SayReducer from "./say_reducer";
import HailNpcReducer from "./hail_npc_reducer";
import CreateTestItemReducer from "./create_test_item_reducer";
import CreateRecipeScrollReducer from "./create_recipe_scroll_reducer";
import GroupMessageReducer from "./group_message_reducer";
import LevelCharacterReducer from "./level_character_reducer";
import RecomputeRacialAllReducer from "./recompute_racial_all_reducer";
import WhisperReducer from "./whisper_reducer";
import CreateGroupReducer from "./create_group_reducer";
import JoinGroupReducer from "./join_group_reducer";
import LeaveGroupReducer from "./leave_group_reducer";
import SetFollowLeaderReducer from "./set_follow_leader_reducer";
import PromoteGroupLeaderReducer from "./promote_group_leader_reducer";
import SetGroupPullerReducer from "./set_group_puller_reducer";
import KickGroupMemberReducer from "./kick_group_member_reducer";
import InviteToGroupReducer from "./invite_to_group_reducer";
import AcceptGroupInviteReducer from "./accept_group_invite_reducer";
import RejectGroupInviteReducer from "./reject_group_invite_reducer";
import StartCombatReducer from "./start_combat_reducer";
import StartTrackedCombatReducer from "./start_tracked_combat_reducer";
import StartPullReducer from "./start_pull_reducer";
import SetCombatTargetReducer from "./set_combat_target_reducer";
import FleeCombatReducer from "./flee_combat_reducer";
import DismissCombatResultsReducer from "./dismiss_combat_results_reducer";
import EndCombatReducer from "./end_combat_reducer";
import LootCorpseItemReducer from "./loot_corpse_item_reducer";
import LootAllCorpseReducer from "./loot_all_corpse_reducer";
import InitiateResurrectReducer from "./initiate_resurrect_reducer";
import AcceptResurrectReducer from "./accept_resurrect_reducer";
import DeclineResurrectReducer from "./decline_resurrect_reducer";
import InitiateCorpseSummonReducer from "./initiate_corpse_summon_reducer";
import AcceptCorpseSummonReducer from "./accept_corpse_summon_reducer";
import DeclineCorpseSummonReducer from "./decline_corpse_summon_reducer";
import SpawnCorpseReducer from "./spawn_corpse_reducer";
import EatFoodReducer from "./eat_food_reducer";
import ChooseDialogueOptionReducer from "./choose_dialogue_option_reducer";
import GiveGiftToNpcReducer from "./give_gift_to_npc_reducer";
import LootQuestItemReducer from "./loot_quest_item_reducer";
import PullNamedEnemyReducer from "./pull_named_enemy_reducer";
import ChoosePerkReducer from "./choose_perk_reducer";
import GrantTestRenownReducer from "./grant_test_renown_reducer";
import GrantTestAchievementReducer from "./grant_test_achievement_reducer";
import SavePanelLayoutReducer from "./save_panel_layout_reducer";
import FireWorldEventReducer from "./fire_world_event_reducer";
import ResolveWorldEventReducer from "./resolve_world_event_reducer";
import CollectEventItemReducer from "./collect_event_item_reducer";
import IncrementEventCounterReducer from "./increment_event_counter_reducer";
import DepositToBankReducer from "./deposit_to_bank_reducer";
import WithdrawFromBankReducer from "./withdraw_from_bank_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AbilityCooldownRow from "./ability_cooldown_table";
import AbilityTemplateRow from "./ability_template_table";
import AchievementRow from "./achievement_table";
import ActiveBardSongRow from "./active_bard_song_table";
import ActivePetRow from "./active_pet_table";
import AppVersionRow from "./app_version_table";
import CharacterRow from "./character_table";
import CharacterCastRow from "./character_cast_table";
import CharacterEffectRow from "./character_effect_table";
import CharacterLogoutTickRow from "./character_logout_tick_table";
import CombatEncounterRow from "./combat_encounter_table";
import CombatEnemyRow from "./combat_enemy_table";
import CombatEnemyCastRow from "./combat_enemy_cast_table";
import CombatEnemyCooldownRow from "./combat_enemy_cooldown_table";
import CombatEnemyEffectRow from "./combat_enemy_effect_table";
import CombatLootRow from "./combat_loot_table";
import CombatParticipantRow from "./combat_participant_table";
import CombatPendingAddRow from "./combat_pending_add_table";
import CombatResultRow from "./combat_result_table";
import CommandRow from "./command_table";
import CorpseRow from "./corpse_table";
import CorpseItemRow from "./corpse_item_table";
import EnemyAbilityRow from "./enemy_ability_table";
import EnemyRoleTemplateRow from "./enemy_role_template_table";
import EnemySpawnRow from "./enemy_spawn_table";
import EnemySpawnMemberRow from "./enemy_spawn_member_table";
import EnemyTemplateRow from "./enemy_template_table";
import EventContributionRow from "./event_contribution_table";
import EventGroupRow from "./event_group_table";
import EventLocationRow from "./event_location_table";
import EventObjectiveRow from "./event_objective_table";
import EventPrivateRow from "./event_private_table";
import EventSpawnEnemyRow from "./event_spawn_enemy_table";
import EventSpawnItemRow from "./event_spawn_item_table";
import EventWorldRow from "./event_world_table";
import FactionRow from "./faction_table";
import FactionStandingRow from "./faction_standing_table";
import FriendRow from "./friend_table";
import FriendRequestRow from "./friend_request_table";
import GroupRow from "./group_table";
import GroupInviteRow from "./group_invite_table";
import GroupMemberRow from "./group_member_table";
import HotbarSlotRow from "./hotbar_slot_table";
import ItemAffixRow from "./item_affix_table";
import ItemCooldownRow from "./item_cooldown_table";
import ItemInstanceRow from "./item_instance_table";
import ItemTemplateRow from "./item_template_table";
import LocationRow from "./location_table";
import LocationConnectionRow from "./location_connection_table";
import LootTableRow from "./loot_table_table";
import MyBankSlotsRow from "./my_bank_slots_table";
import MyCharacterEffectsRow from "./my_character_effects_table";
import MyCombatLootRow from "./my_combat_loot_table";
import MyCombatResultsRow from "./my_combat_results_table";
import MyFactionStandingsRow from "./my_faction_standings_table";
import MyFriendRequestsRow from "./my_friend_requests_table";
import MyFriendsRow from "./my_friends_table";
import MyGroupEventsRow from "./my_group_events_table";
import MyGroupInvitesRow from "./my_group_invites_table";
import MyGroupMembersRow from "./my_group_members_table";
import MyLocationEventsRow from "./my_location_events_table";
import MyNpcDialogRow from "./my_npc_dialog_table";
import MyPanelLayoutRow from "./my_panel_layout_table";
import MyPlayerRow from "./my_player_table";
import MyPrivateEventsRow from "./my_private_events_table";
import MyQuestsRow from "./my_quests_table";
import NamedEnemyRow from "./named_enemy_table";
import NpcRow from "./npc_table";
import NpcAffinityRow from "./npc_affinity_table";
import NpcDialogRow from "./npc_dialog_table";
import NpcDialogueOptionRow from "./npc_dialogue_option_table";
import NpcDialogueVisitedRow from "./npc_dialogue_visited_table";
import PendingSpellCastRow from "./pending_spell_cast_table";
import PlayerRow from "./player_table";
import PullStateRow from "./pull_state_table";
import PullTickRow from "./pull_tick_table";
import QuestInstanceRow from "./quest_instance_table";
import QuestItemRow from "./quest_item_table";
import QuestTemplateRow from "./quest_template_table";
import RaceRow from "./race_table";
import RecipeDiscoveredRow from "./recipe_discovered_table";
import RecipeTemplateRow from "./recipe_template_table";
import RegionRow from "./region_table";
import RenownRow from "./renown_table";
import RenownPerkRow from "./renown_perk_table";
import RenownServerFirstRow from "./renown_server_first_table";
import ResourceGatherRow from "./resource_gather_table";
import ResourceNodeRow from "./resource_node_table";
import SearchResultRow from "./search_result_table";
import TradeItemRow from "./trade_item_table";
import TradeSessionRow from "./trade_session_table";
import TravelCooldownRow from "./travel_cooldown_table";
import UiPanelLayoutRow from "./ui_panel_layout_table";
import UserRow from "./user_table";
import VendorInventoryRow from "./vendor_inventory_table";
import WorldEventRow from "./world_event_table";
import WorldStatTrackerRow from "./world_stat_tracker_table";
import WorldStateRow from "./world_state_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ability_cooldown: __table({
    name: 'ability_cooldown',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ability_cooldown_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AbilityCooldownRow),
  ability_template: __table({
    name: 'ability_template',
    indexes: [
      { name: 'by_class', algorithm: 'btree', columns: [
        'className',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'ability_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AbilityTemplateRow),
  achievement: __table({
    name: 'achievement',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'achievement_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AchievementRow),
  active_bard_song: __table({
    name: 'active_bard_song',
    indexes: [
      { name: 'by_bard', algorithm: 'btree', columns: [
        'bardCharacterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'active_bard_song_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActiveBardSongRow),
  active_pet: __table({
    name: 'active_pet',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'active_pet_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivePetRow),
  app_version: __table({
    name: 'app_version',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'app_version_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AppVersionRow),
  character: __table({
    name: 'character',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'character_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterRow),
  character_cast: __table({
    name: 'character_cast',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'character_cast_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterCastRow),
  character_effect: __table({
    name: 'character_effect',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'character_effect_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterEffectRow),
  character_logout_tick: __table({
    name: 'character_logout_tick',
    indexes: [
      { name: 'scheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'character_logout_tick_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, CharacterLogoutTickRow),
  combat_encounter: __table({
    name: 'combat_encounter',
    indexes: [
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'combat_encounter_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatEncounterRow),
  combat_enemy: __table({
    name: 'combat_enemy',
    indexes: [
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_enemy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatEnemyRow),
  combat_enemy_cast: __table({
    name: 'combat_enemy_cast',
    indexes: [
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_enemy_cast_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatEnemyCastRow),
  combat_enemy_cooldown: __table({
    name: 'combat_enemy_cooldown',
    indexes: [
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'by_enemy', algorithm: 'btree', columns: [
        'enemyId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_enemy_cooldown_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatEnemyCooldownRow),
  combat_enemy_effect: __table({
    name: 'combat_enemy_effect',
    indexes: [
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'by_enemy', algorithm: 'btree', columns: [
        'enemyId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_enemy_effect_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatEnemyEffectRow),
  combat_loot: __table({
    name: 'combat_loot',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'combat_loot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatLootRow),
  combat_participant: __table({
    name: 'combat_participant',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_participant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatParticipantRow),
  combat_pending_add: __table({
    name: 'combat_pending_add',
    indexes: [
      { name: 'by_ready', algorithm: 'btree', columns: [
        'arriveAtMicros',
      ] },
      { name: 'by_combat', algorithm: 'btree', columns: [
        'combatId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_pending_add_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatPendingAddRow),
  combat_result: __table({
    name: 'combat_result',
    indexes: [
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'combat_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatResultRow),
  command: __table({
    name: 'command',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'command_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommandRow),
  corpse: __table({
    name: 'corpse',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'corpse_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CorpseRow),
  corpse_item: __table({
    name: 'corpse_item',
    indexes: [
      { name: 'by_corpse', algorithm: 'btree', columns: [
        'corpseId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'corpse_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CorpseItemRow),
  enemy_ability: __table({
    name: 'enemy_ability',
    indexes: [
      { name: 'by_template', algorithm: 'btree', columns: [
        'enemyTemplateId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemy_ability_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyAbilityRow),
  enemy_role_template: __table({
    name: 'enemy_role_template',
    indexes: [
      { name: 'by_template', algorithm: 'btree', columns: [
        'enemyTemplateId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemy_role_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyRoleTemplateRow),
  enemy_spawn: __table({
    name: 'enemy_spawn',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { name: 'by_state', algorithm: 'btree', columns: [
        'state',
      ] },
    ],
    constraints: [
      { name: 'enemy_spawn_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemySpawnRow),
  enemy_spawn_member: __table({
    name: 'enemy_spawn_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_spawn', algorithm: 'btree', columns: [
        'spawnId',
      ] },
    ],
    constraints: [
      { name: 'enemy_spawn_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemySpawnMemberRow),
  enemy_template: __table({
    name: 'enemy_template',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemy_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyTemplateRow),
  event_contribution: __table({
    name: 'event_contribution',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_event', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_contribution_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventContributionRow),
  event_group: __table({
    name: 'event_group',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_group_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventGroupRow),
  event_location: __table({
    name: 'event_location',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'event_location_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventLocationRow),
  event_objective: __table({
    name: 'event_objective',
    indexes: [
      { name: 'by_event', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_objective_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventObjectiveRow),
  event_private: __table({
    name: 'event_private',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'event_private_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventPrivateRow),
  event_spawn_enemy: __table({
    name: 'event_spawn_enemy',
    indexes: [
      { name: 'by_event', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_spawn', algorithm: 'btree', columns: [
        'spawnId',
      ] },
    ],
    constraints: [
      { name: 'event_spawn_enemy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventSpawnEnemyRow),
  event_spawn_item: __table({
    name: 'event_spawn_item',
    indexes: [
      { name: 'by_event', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'event_spawn_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventSpawnItemRow),
  event_world: __table({
    name: 'event_world',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_world_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventWorldRow),
  faction: __table({
    name: 'faction',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'faction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FactionRow),
  faction_standing: __table({
    name: 'faction_standing',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'faction_standing_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FactionStandingRow),
  friend: __table({
    name: 'friend',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_user', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'friend_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendRow),
  friend_request: __table({
    name: 'friend_request',
    indexes: [
      { name: 'by_from', algorithm: 'btree', columns: [
        'fromUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_to', algorithm: 'btree', columns: [
        'toUserId',
      ] },
    ],
    constraints: [
      { name: 'friend_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendRequestRow),
  group: __table({
    name: 'group',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'group_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupRow),
  group_invite: __table({
    name: 'group_invite',
    indexes: [
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_to_character', algorithm: 'btree', columns: [
        'toCharacterId',
      ] },
    ],
    constraints: [
      { name: 'group_invite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupInviteRow),
  group_member: __table({
    name: 'group_member',
    indexes: [
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'group_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupMemberRow),
  hotbar_slot: __table({
    name: 'hotbar_slot',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hotbar_slot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HotbarSlotRow),
  item_affix: __table({
    name: 'item_affix',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_instance', algorithm: 'btree', columns: [
        'itemInstanceId',
      ] },
    ],
    constraints: [
      { name: 'item_affix_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemAffixRow),
  item_cooldown: __table({
    name: 'item_cooldown',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'item_cooldown_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemCooldownRow),
  item_instance: __table({
    name: 'item_instance',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner', algorithm: 'btree', columns: [
        'ownerCharacterId',
      ] },
    ],
    constraints: [
      { name: 'item_instance_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemInstanceRow),
  item_template: __table({
    name: 'item_template',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'item_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ItemTemplateRow),
  location: __table({
    name: 'location',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'location_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LocationRow),
  location_connection: __table({
    name: 'location_connection',
    indexes: [
      { name: 'by_from', algorithm: 'btree', columns: [
        'fromLocationId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_to', algorithm: 'btree', columns: [
        'toLocationId',
      ] },
    ],
    constraints: [
      { name: 'location_connection_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LocationConnectionRow),
  loot_table: __table({
    name: 'loot_table',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_key', algorithm: 'btree', columns: [
        'terrainType',
        'creatureType',
        'tier',
      ] },
    ],
    constraints: [
      { name: 'loot_table_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LootTableRow),
  named_enemy: __table({
    name: 'named_enemy',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'named_enemy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NamedEnemyRow),
  npc: __table({
    name: 'npc',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'npc_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcRow),
  npc_affinity: __table({
    name: 'npc_affinity',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_npc', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_affinity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcAffinityRow),
  npc_dialog: __table({
    name: 'npc_dialog',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_npc', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_dialog_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcDialogRow),
  npc_dialogue_option: __table({
    name: 'npc_dialogue_option',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_npc', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'npc_dialogue_option_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcDialogueOptionRow),
  npc_dialogue_visited: __table({
    name: 'npc_dialogue_visited',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'npc_dialogue_visited_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NpcDialogueVisitedRow),
  pending_spell_cast: __table({
    name: 'pending_spell_cast',
    indexes: [
      { name: 'by_caster', algorithm: 'btree', columns: [
        'casterCharacterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_target', algorithm: 'btree', columns: [
        'targetCharacterId',
      ] },
    ],
    constraints: [
      { name: 'pending_spell_cast_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PendingSpellCastRow),
  player: __table({
    name: 'player',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerRow),
  pull_state: __table({
    name: 'pull_state',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { name: 'by_state', algorithm: 'btree', columns: [
        'state',
      ] },
    ],
    constraints: [
      { name: 'pull_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PullStateRow),
  pull_tick: __table({
    name: 'pull_tick',
    indexes: [
      { name: 'by_pull', algorithm: 'btree', columns: [
        'pullId',
      ] },
      { name: 'scheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'pull_tick_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PullTickRow),
  quest_instance: __table({
    name: 'quest_instance',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_template', algorithm: 'btree', columns: [
        'questTemplateId',
      ] },
    ],
    constraints: [
      { name: 'quest_instance_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestInstanceRow),
  quest_item: __table({
    name: 'quest_item',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'quest_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestItemRow),
  quest_template: __table({
    name: 'quest_template',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_npc', algorithm: 'btree', columns: [
        'npcId',
      ] },
      { name: 'by_enemy', algorithm: 'btree', columns: [
        'targetEnemyTemplateId',
      ] },
    ],
    constraints: [
      { name: 'quest_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestTemplateRow),
  race: __table({
    name: 'race',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'race_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RaceRow),
  recipe_discovered: __table({
    name: 'recipe_discovered',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'recipe_discovered_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RecipeDiscoveredRow),
  recipe_template: __table({
    name: 'recipe_template',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'recipe_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RecipeTemplateRow),
  region: __table({
    name: 'region',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'region_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RegionRow),
  renown: __table({
    name: 'renown',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'renown_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RenownRow),
  renown_perk: __table({
    name: 'renown_perk',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'renown_perk_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RenownPerkRow),
  renown_server_first: __table({
    name: 'renown_server_first',
    indexes: [
      { name: 'by_category', algorithm: 'btree', columns: [
        'category',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'renown_server_first_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RenownServerFirstRow),
  resource_gather: __table({
    name: 'resource_gather',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'resource_gather_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ResourceGatherRow),
  resource_node: __table({
    name: 'resource_node',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'resource_node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ResourceNodeRow),
  search_result: __table({
    name: 'search_result',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'search_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SearchResultRow),
  trade_item: __table({
    name: 'trade_item',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'fromCharacterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_trade', algorithm: 'btree', columns: [
        'tradeId',
      ] },
    ],
    constraints: [
      { name: 'trade_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TradeItemRow),
  trade_session: __table({
    name: 'trade_session',
    indexes: [
      { name: 'by_from', algorithm: 'btree', columns: [
        'fromCharacterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_to', algorithm: 'btree', columns: [
        'toCharacterId',
      ] },
    ],
    constraints: [
      { name: 'trade_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TradeSessionRow),
  travel_cooldown: __table({
    name: 'travel_cooldown',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'travel_cooldown_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TravelCooldownRow),
  ui_panel_layout: __table({
    name: 'ui_panel_layout',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ui_panel_layout_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UiPanelLayoutRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'by_email', algorithm: 'btree', columns: [
        'email',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRow),
  vendor_inventory: __table({
    name: 'vendor_inventory',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_vendor', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'vendor_inventory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VendorInventoryRow),
  world_event: __table({
    name: 'world_event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_region', algorithm: 'btree', columns: [
        'regionId',
      ] },
      { name: 'by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'world_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldEventRow),
  world_stat_tracker: __table({
    name: 'world_stat_tracker',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_stat_key', algorithm: 'btree', columns: [
        'statKey',
      ] },
    ],
    constraints: [
      { name: 'world_stat_tracker_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldStatTrackerRow),
  world_state: __table({
    name: 'world_state',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldStateRow),
  my_bank_slots: __table({
    name: 'my_bank_slots',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBankSlotsRow),
  my_character_effects: __table({
    name: 'my_character_effects',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCharacterEffectsRow),
  my_combat_loot: __table({
    name: 'my_combat_loot',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCombatLootRow),
  my_combat_results: __table({
    name: 'my_combat_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCombatResultsRow),
  my_faction_standings: __table({
    name: 'my_faction_standings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFactionStandingsRow),
  my_friend_requests: __table({
    name: 'my_friend_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendRequestsRow),
  my_friends: __table({
    name: 'my_friends',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendsRow),
  my_group_events: __table({
    name: 'my_group_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGroupEventsRow),
  my_group_invites: __table({
    name: 'my_group_invites',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGroupInvitesRow),
  my_group_members: __table({
    name: 'my_group_members',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGroupMembersRow),
  my_location_events: __table({
    name: 'my_location_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLocationEventsRow),
  my_npc_dialog: __table({
    name: 'my_npc_dialog',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNpcDialogRow),
  my_panel_layout: __table({
    name: 'my_panel_layout',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPanelLayoutRow),
  my_player: __table({
    name: 'my_player',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerRow),
  my_private_events: __table({
    name: 'my_private_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPrivateEventsRow),
  my_quests: __table({
    name: 'my_quests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyQuestsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("set_app_version", SetAppVersionReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("send_friend_request_to_character", SendFriendRequestToCharacterReducer),
  __reducerSchema("accept_friend_request", AcceptFriendRequestReducer),
  __reducerSchema("reject_friend_request", RejectFriendRequestReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("login_email", LoginEmailReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("set_active_character", SetActiveCharacterReducer),
  __reducerSchema("clear_active_character", ClearActiveCharacterReducer),
  __reducerSchema("create_character", CreateCharacterReducer),
  __reducerSchema("bind_location", BindLocationReducer),
  __reducerSchema("delete_character", DeleteCharacterReducer),
  __reducerSchema("respawn_character", RespawnCharacterReducer),
  __reducerSchema("create_item_template", CreateItemTemplateReducer),
  __reducerSchema("grant_item", GrantItemReducer),
  __reducerSchema("buy_item", BuyItemReducer),
  __reducerSchema("sell_item", SellItemReducer),
  __reducerSchema("sell_all_junk", SellAllJunkReducer),
  __reducerSchema("take_loot", TakeLootReducer),
  __reducerSchema("take_all_loot", TakeAllLootReducer),
  __reducerSchema("equip_item", EquipItemReducer),
  __reducerSchema("unequip_item", UnequipItemReducer),
  __reducerSchema("delete_item", DeleteItemReducer),
  __reducerSchema("split_stack", SplitStackReducer),
  __reducerSchema("consolidate_stacks", ConsolidateStacksReducer),
  __reducerSchema("set_hotbar_slot", SetHotbarSlotReducer),
  __reducerSchema("use_ability", UseAbilityReducer),
  __reducerSchema("use_item", UseItemReducer),
  __reducerSchema("sync_equipment_tables", SyncEquipmentTablesReducer),
  __reducerSchema("sync_loot_tables", SyncLootTablesReducer),
  __reducerSchema("sync_enemy_content", SyncEnemyContentReducer),
  __reducerSchema("sync_world_layout", SyncWorldLayoutReducer),
  __reducerSchema("sync_ability_templates", SyncAbilityTemplatesReducer),
  __reducerSchema("sync_recipe_templates", SyncRecipeTemplatesReducer),
  __reducerSchema("sync_npc_quest_content", SyncNpcQuestContentReducer),
  __reducerSchema("sync_all_content", SyncAllContentReducer),
  __reducerSchema("research_recipes", ResearchRecipesReducer),
  __reducerSchema("craft_recipe", CraftRecipeReducer),
  __reducerSchema("learn_recipe_scroll", LearnRecipeScrollReducer),
  __reducerSchema("salvage_item", SalvageItemReducer),
  __reducerSchema("start_gather_resource", StartGatherResourceReducer),
  __reducerSchema("start_trade", StartTradeReducer),
  __reducerSchema("add_trade_item", AddTradeItemReducer),
  __reducerSchema("remove_trade_item", RemoveTradeItemReducer),
  __reducerSchema("offer_trade", OfferTradeReducer),
  __reducerSchema("cancel_trade", CancelTradeReducer),
  __reducerSchema("move_character", MoveCharacterReducer),
  __reducerSchema("submit_command", SubmitCommandReducer),
  __reducerSchema("say", SayReducer),
  __reducerSchema("hail_npc", HailNpcReducer),
  __reducerSchema("create_test_item", CreateTestItemReducer),
  __reducerSchema("create_recipe_scroll", CreateRecipeScrollReducer),
  __reducerSchema("group_message", GroupMessageReducer),
  __reducerSchema("level_character", LevelCharacterReducer),
  __reducerSchema("recompute_racial_all", RecomputeRacialAllReducer),
  __reducerSchema("whisper", WhisperReducer),
  __reducerSchema("create_group", CreateGroupReducer),
  __reducerSchema("join_group", JoinGroupReducer),
  __reducerSchema("leave_group", LeaveGroupReducer),
  __reducerSchema("set_follow_leader", SetFollowLeaderReducer),
  __reducerSchema("promote_group_leader", PromoteGroupLeaderReducer),
  __reducerSchema("set_group_puller", SetGroupPullerReducer),
  __reducerSchema("kick_group_member", KickGroupMemberReducer),
  __reducerSchema("invite_to_group", InviteToGroupReducer),
  __reducerSchema("accept_group_invite", AcceptGroupInviteReducer),
  __reducerSchema("reject_group_invite", RejectGroupInviteReducer),
  __reducerSchema("start_combat", StartCombatReducer),
  __reducerSchema("start_tracked_combat", StartTrackedCombatReducer),
  __reducerSchema("start_pull", StartPullReducer),
  __reducerSchema("set_combat_target", SetCombatTargetReducer),
  __reducerSchema("flee_combat", FleeCombatReducer),
  __reducerSchema("dismiss_combat_results", DismissCombatResultsReducer),
  __reducerSchema("end_combat", EndCombatReducer),
  __reducerSchema("loot_corpse_item", LootCorpseItemReducer),
  __reducerSchema("loot_all_corpse", LootAllCorpseReducer),
  __reducerSchema("initiate_resurrect", InitiateResurrectReducer),
  __reducerSchema("accept_resurrect", AcceptResurrectReducer),
  __reducerSchema("decline_resurrect", DeclineResurrectReducer),
  __reducerSchema("initiate_corpse_summon", InitiateCorpseSummonReducer),
  __reducerSchema("accept_corpse_summon", AcceptCorpseSummonReducer),
  __reducerSchema("decline_corpse_summon", DeclineCorpseSummonReducer),
  __reducerSchema("spawn_corpse", SpawnCorpseReducer),
  __reducerSchema("eat_food", EatFoodReducer),
  __reducerSchema("choose_dialogue_option", ChooseDialogueOptionReducer),
  __reducerSchema("give_gift_to_npc", GiveGiftToNpcReducer),
  __reducerSchema("loot_quest_item", LootQuestItemReducer),
  __reducerSchema("pull_named_enemy", PullNamedEnemyReducer),
  __reducerSchema("choose_perk", ChoosePerkReducer),
  __reducerSchema("grant_test_renown", GrantTestRenownReducer),
  __reducerSchema("grant_test_achievement", GrantTestAchievementReducer),
  __reducerSchema("save_panel_layout", SavePanelLayoutReducer),
  __reducerSchema("fire_world_event", FireWorldEventReducer),
  __reducerSchema("resolve_world_event", ResolveWorldEventReducer),
  __reducerSchema("collect_event_item", CollectEventItemReducer),
  __reducerSchema("increment_event_counter", IncrementEventCounterReducer),
  __reducerSchema("deposit_to_bank", DepositToBankReducer),
  __reducerSchema("withdraw_from_bank", WithdrawFromBankReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

