// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.12.0 (commit 92fdc93b9507ac89061cafb4f4909b3a1162e59d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import OnConnectReducer from "./on_connect_reducer";
export { OnConnectReducer };
import OnDisconnectReducer from "./on_disconnect_reducer";
export { OnDisconnectReducer };
import SetDisplayNameReducer from "./set_display_name_reducer";
export { SetDisplayNameReducer };
import LoginEmailReducer from "./login_email_reducer";
export { LoginEmailReducer };
import LogoutReducer from "./logout_reducer";
export { LogoutReducer };
import SetActiveCharacterReducer from "./set_active_character_reducer";
export { SetActiveCharacterReducer };
import CreateCharacterReducer from "./create_character_reducer";
export { CreateCharacterReducer };
import MoveCharacterReducer from "./move_character_reducer";
export { MoveCharacterReducer };
import SubmitCommandReducer from "./submit_command_reducer";
export { SubmitCommandReducer };
import SayReducer from "./say_reducer";
export { SayReducer };
import StartCombatReducer from "./start_combat_reducer";
export { StartCombatReducer };
import CreateGroupReducer from "./create_group_reducer";
export { CreateGroupReducer };
import JoinGroupReducer from "./join_group_reducer";
export { JoinGroupReducer };
import LeaveGroupReducer from "./leave_group_reducer";
export { LeaveGroupReducer };
import AttackReducer from "./attack_reducer";
export { AttackReducer };
import EndCombatReducer from "./end_combat_reducer";
export { EndCombatReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import CharacterRow from "./character_table";
export { CharacterRow };
import CombatRow from "./combat_table";
export { CombatRow };
import CommandRow from "./command_table";
export { CommandRow };
import EnemyTemplateRow from "./enemy_template_table";
export { EnemyTemplateRow };
import EventGroupRow from "./event_group_table";
export { EventGroupRow };
import EventLocationRow from "./event_location_table";
export { EventLocationRow };
import EventPrivateRow from "./event_private_table";
export { EventPrivateRow };
import EventWorldRow from "./event_world_table";
export { EventWorldRow };
import GroupRow from "./group_table";
export { GroupRow };
import GroupMemberRow from "./group_member_table";
export { GroupMemberRow };
import LocationRow from "./location_table";
export { LocationRow };
import MyGroupEventsRow from "./my_group_events_table";
export { MyGroupEventsRow };
import MyLocationEventsRow from "./my_location_events_table";
export { MyLocationEventsRow };
import MyPlayerRow from "./my_player_table";
export { MyPlayerRow };
import MyPrivateEventsRow from "./my_private_events_table";
export { MyPrivateEventsRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import UserRow from "./user_table";
export { UserRow };
import WorldStateRow from "./world_state_table";
export { WorldStateRow };

// Import and reexport all types
import Attack from "./attack_type";
export { Attack };
import Character from "./character_type";
export { Character };
import Combat from "./combat_type";
export { Combat };
import Command from "./command_type";
export { Command };
import CreateCharacter from "./create_character_type";
export { CreateCharacter };
import CreateGroup from "./create_group_type";
export { CreateGroup };
import EndCombat from "./end_combat_type";
export { EndCombat };
import EnemyTemplate from "./enemy_template_type";
export { EnemyTemplate };
import EventGroup from "./event_group_type";
export { EventGroup };
import EventLocation from "./event_location_type";
export { EventLocation };
import EventPrivate from "./event_private_type";
export { EventPrivate };
import EventWorld from "./event_world_type";
export { EventWorld };
import Group from "./group_type";
export { Group };
import GroupMember from "./group_member_type";
export { GroupMember };
import Init from "./init_type";
export { Init };
import JoinGroup from "./join_group_type";
export { JoinGroup };
import LeaveGroup from "./leave_group_type";
export { LeaveGroup };
import Location from "./location_type";
export { Location };
import LoginEmail from "./login_email_type";
export { LoginEmail };
import Logout from "./logout_type";
export { Logout };
import MoveCharacter from "./move_character_type";
export { MoveCharacter };
import MyGroupEvents from "./my_group_events_type";
export { MyGroupEvents };
import MyLocationEvents from "./my_location_events_type";
export { MyLocationEvents };
import MyPlayer from "./my_player_type";
export { MyPlayer };
import MyPrivateEvents from "./my_private_events_type";
export { MyPrivateEvents };
import OnConnect from "./on_connect_type";
export { OnConnect };
import OnDisconnect from "./on_disconnect_type";
export { OnDisconnect };
import Player from "./player_type";
export { Player };
import Say from "./say_type";
export { Say };
import SetActiveCharacter from "./set_active_character_type";
export { SetActiveCharacter };
import SetDisplayName from "./set_display_name_type";
export { SetDisplayName };
import StartCombat from "./start_combat_type";
export { StartCombat };
import SubmitCommand from "./submit_command_type";
export { SubmitCommand };
import User from "./user_type";
export { User };
import WorldState from "./world_state_type";
export { WorldState };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'character',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'character_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CharacterRow),
  __table({
    name: 'combat',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'combat_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CombatRow),
  __table({
    name: 'command',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'command_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommandRow),
  __table({
    name: 'enemy_template',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemy_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyTemplateRow),
  __table({
    name: 'event_group',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_group_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventGroupRow),
  __table({
    name: 'event_location',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_location', algorithm: 'btree', columns: [
        'locationId',
      ] },
    ],
    constraints: [
      { name: 'event_location_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventLocationRow),
  __table({
    name: 'event_private',
    indexes: [
      { name: 'by_character', algorithm: 'btree', columns: [
        'characterId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'event_private_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventPrivateRow),
  __table({
    name: 'event_world',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'event_world_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventWorldRow),
  __table({
    name: 'group',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'group_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupRow),
  __table({
    name: 'group_member',
    indexes: [
      { name: 'by_group', algorithm: 'btree', columns: [
        'groupId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'by_owner_user', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'group_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroupMemberRow),
  __table({
    name: 'location',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'location_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LocationRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerRow),
  __table({
    name: 'user',
    indexes: [
      { name: 'by_email', algorithm: 'btree', columns: [
        'email',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRow),
  __table({
    name: 'world_state',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldStateRow),
  __table({
    name: 'my_group_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGroupEventsRow),
  __table({
    name: 'my_location_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLocationEventsRow),
  __table({
    name: 'my_player',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerRow),
  __table({
    name: 'my_private_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPrivateEventsRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("login_email", LoginEmailReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("set_active_character", SetActiveCharacterReducer),
  __reducerSchema("create_character", CreateCharacterReducer),
  __reducerSchema("move_character", MoveCharacterReducer),
  __reducerSchema("submit_command", SubmitCommandReducer),
  __reducerSchema("say", SayReducer),
  __reducerSchema("start_combat", StartCombatReducer),
  __reducerSchema("create_group", CreateGroupReducer),
  __reducerSchema("join_group", JoinGroupReducer),
  __reducerSchema("leave_group", LeaveGroupReducer),
  __reducerSchema("attack", AttackReducer),
  __reducerSchema("end_combat", EndCombatReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.12.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** A typed query builder for this remote SpacetimeDB module. */
export const query: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

