// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  itemInstanceId: __t.u64().name("item_instance_id"),
  affixType: __t.string().name("affix_type"),
  affixKey: __t.string().name("affix_key"),
  affixName: __t.string().name("affix_name"),
  statKey: __t.string().name("stat_key"),
  magnitude: __t.i64(),
});
