// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  slot: __t.string(),
  armorType: __t.string(),
  rarity: __t.string(),
  requiredLevel: __t.u64(),
  allowedClasses: __t.string(),
  strBonus: __t.u64(),
  dexBonus: __t.u64(),
  chaBonus: __t.u64(),
  wisBonus: __t.u64(),
  intBonus: __t.u64(),
  hpBonus: __t.u64(),
  manaBonus: __t.u64(),
  armorClassBonus: __t.u64(),
  weaponBaseDamage: __t.u64(),
  weaponDps: __t.u64(),
});
