// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  templateId: __t.u64().name("template_id"),
  ownerCharacterId: __t.u64().name("owner_character_id"),
  equippedSlot: __t.option(__t.string()).name("equipped_slot"),
  quantity: __t.u64(),
  qualityTier: __t.option(__t.string()).name("quality_tier"),
  craftQuality: __t.option(__t.string()).name("craft_quality"),
  displayName: __t.option(__t.string()).name("display_name"),
  isNamed: __t.option(__t.bool()).name("is_named"),
  isTemporary: __t.option(__t.bool()).name("is_temporary"),
});
