// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.identity().name("player_id"),
  domain: __t.string(),
  model: __t.string(),
  systemPrompt: __t.string().name("system_prompt"),
  userPrompt: __t.string().name("user_prompt"),
  maxTokens: __t.u64().name("max_tokens"),
  status: __t.string(),
  contextJson: __t.option(__t.string()).name("context_json"),
  responseFormatJson: __t.option(__t.string()).name("response_format_json"),
  createdAt: __t.timestamp().name("created_at"),
});
