// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Location", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  zone: __t.string(),
  regionId: __t.u64(),
  levelOffset: __t.i64(),
  isSafe: __t.bool(),
  terrainType: __t.string(),
  bindStone: __t.bool(),
});


