// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  terrainType: __t.string().name("terrain_type"),
  creatureType: __t.string().name("creature_type"),
  tier: __t.u64(),
  junkChance: __t.u64().name("junk_chance"),
  gearChance: __t.u64().name("gear_chance"),
  goldMin: __t.u64().name("gold_min"),
  goldMax: __t.u64().name("gold_max"),
});
