// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  combatId: __t.u64().name("combat_id"),
  ownerUserId: __t.u64().name("owner_user_id"),
  characterId: __t.u64().name("character_id"),
  itemTemplateId: __t.u64().name("item_template_id"),
  createdAt: __t.timestamp().name("created_at"),
  qualityTier: __t.option(__t.string()).name("quality_tier"),
  affixDataJson: __t.option(__t.string()).name("affix_data_json"),
  isNamed: __t.option(__t.bool()).name("is_named"),
  craftQuality: __t.option(__t.string()).name("craft_quality"),
});
