// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  displayName: __t.option(__t.string()).name("display_name"),
  activeCharacterId: __t.option(__t.u64()).name("active_character_id"),
  userId: __t.option(__t.u64()).name("user_id"),
  sessionStartedAt: __t.option(__t.timestamp()).name("session_started_at"),
  lastActivityAt: __t.option(__t.timestamp()).name("last_activity_at"),
});
