// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  npcId: __t.u64().name("npc_id"),
  npcName: __t.string().name("npc_name"),
  locationId: __t.u64().name("location_id"),
  templateId: __t.u64().name("template_id"),
  itemName: __t.string().name("item_name"),
  rarity: __t.string(),
  quantity: __t.u64(),
  price: __t.u64(),
  qualityTier: __t.option(__t.string()).name("quality_tier"),
  craftQuality: __t.option(__t.string()).name("craft_quality"),
  displayName: __t.option(__t.string()).name("display_name"),
  isNamed: __t.option(__t.bool()).name("is_named"),
  isTemporary: __t.option(__t.bool()).name("is_temporary"),
  affixesJson: __t.string().name("affixes_json"),
  listingId: __t.option(__t.u64()).name("listing_id"),
  soldAt: __t.timestamp().name("sold_at"),
});
