// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NamedEnemy", {
  id: __t.u64(),
  characterId: __t.u64(),
  name: __t.string(),
  enemyTemplateId: __t.u64(),
  locationId: __t.u64(),
  isAlive: __t.bool(),
  lastKilledAt: __t.option(__t.timestamp()),
  respawnMinutes: __t.u64(),
});


