// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  npcType: __t.string().name("npc_type"),
  locationId: __t.u64().name("location_id"),
  description: __t.string(),
  greeting: __t.string(),
  factionId: __t.option(__t.u64()).name("faction_id"),
  personalityJson: __t.option(__t.string()).name("personality_json"),
  baseMood: __t.option(__t.string()).name("base_mood"),
});
