// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  rank: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  kind: __t.string(),
  targetRule: __t.string().name("target_rule"),
  resourceType: __t.string().name("resource_type"),
  resourceCost: __t.u64().name("resource_cost"),
  castSeconds: __t.u64().name("cast_seconds"),
  cooldownSeconds: __t.u64().name("cooldown_seconds"),
  scaling: __t.string(),
  value1: __t.u64().name("value_1"),
  value2: __t.option(__t.u64()).name("value_2"),
  damageType: __t.option(__t.string()).name("damage_type"),
  effectType: __t.option(__t.string()).name("effect_type"),
  effectMagnitude: __t.option(__t.u64()).name("effect_magnitude"),
  effectDuration: __t.option(__t.u64()).name("effect_duration"),
  perkEffectJson: __t.option(__t.string()).name("perk_effect_json"),
  perkDomain: __t.option(__t.string()).name("perk_domain"),
  createdAt: __t.timestamp().name("created_at"),
});
