// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  regionId: __t.u64().name("region_id"),
  locationId: __t.u64().name("location_id"),
  kind: __t.string(),
  refId: __t.u64().name("ref_id"),
  level: __t.u64(),
  lvLo: __t.u64().name("lv_lo"),
  lvHi: __t.u64().name("lv_hi"),
  name: __t.string(),
  iconKey: __t.string().name("icon_key"),
  temperament: __t.string(),
  singularNoun: __t.string().name("singular_noun"),
  pluralNoun: __t.string().name("plural_noun"),
  timeOfDay: __t.string().name("time_of_day"),
});
