// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  npcId: __t.u64().name("npc_id"),
  targetEnemyTemplateId: __t.u64().name("target_enemy_template_id"),
  requiredCount: __t.u64().name("required_count"),
  minLevel: __t.u64().name("min_level"),
  maxLevel: __t.u64().name("max_level"),
  rewardXp: __t.u64().name("reward_xp"),
  questType: __t.option(__t.string()).name("quest_type"),
  targetLocationId: __t.option(__t.u64()).name("target_location_id"),
  targetNpcId: __t.option(__t.u64()).name("target_npc_id"),
  targetItemName: __t.option(__t.string()).name("target_item_name"),
  itemDropChance: __t.option(__t.u64()).name("item_drop_chance"),
});
