// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Race", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  availableClasses: __t.string(),
  bonus1Type: __t.string(),
  bonus1Value: __t.u64(),
  bonus2Type: __t.string(),
  bonus2Value: __t.u64(),
  unlocked: __t.bool(),
});


