// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("RecipeTemplate", {
  id: __t.u64(),
  key: __t.string(),
  name: __t.string(),
  outputTemplateId: __t.u64(),
  outputCount: __t.u64(),
  req1TemplateId: __t.u64(),
  req1Count: __t.u64(),
  req2TemplateId: __t.u64(),
  req2Count: __t.u64(),
  req3TemplateId: __t.option(__t.u64()),
  req3Count: __t.option(__t.u64()),
});


