// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("RenownServerFirst", {
  id: __t.u64(),
  category: __t.string(),
  achievementKey: __t.string(),
  characterId: __t.u64(),
  characterName: __t.string(),
  achievedAt: __t.timestamp(),
  position: __t.u64(),
});


