// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AbilityCooldown = __t.object("AbilityCooldown", {
  id: __t.u64(),
  characterId: __t.u64(),
  abilityKey: __t.string(),
  startedAtMicros: __t.u64(),
  durationMicros: __t.u64(),
});
export type AbilityCooldown = __Infer<typeof AbilityCooldown>;

export const AbilityTemplate = __t.object("AbilityTemplate", {
  id: __t.u64(),
  key: __t.string(),
  name: __t.string(),
  className: __t.string(),
  level: __t.u64(),
  resource: __t.string(),
  castSeconds: __t.u64(),
  cooldownSeconds: __t.u64(),
  kind: __t.string(),
  combatState: __t.string(),
  description: __t.string(),
  power: __t.option(__t.u64()),
  damageType: __t.option(__t.string()),
  statScaling: __t.option(__t.string()),
  dotPowerSplit: __t.option(__t.f64()),
  dotDuration: __t.option(__t.u64()),
  hotPowerSplit: __t.option(__t.f64()),
  hotDuration: __t.option(__t.u64()),
  debuffType: __t.option(__t.string()),
  debuffMagnitude: __t.option(__t.i64()),
  debuffDuration: __t.option(__t.u64()),
  aoeTargets: __t.option(__t.string()),
  resourceCost: __t.u64(),
});
export type AbilityTemplate = __Infer<typeof AbilityTemplate>;

export const Achievement = __t.object("Achievement", {
  id: __t.u64(),
  characterId: __t.u64(),
  achievementKey: __t.string(),
  achievedAt: __t.timestamp(),
});
export type Achievement = __Infer<typeof Achievement>;

export const ActiveBardSong = __t.object("ActiveBardSong", {
  id: __t.u64(),
  bardCharacterId: __t.u64(),
  combatId: __t.option(__t.u64()),
  songKey: __t.string(),
  startedAtMicros: __t.u64(),
  isFading: __t.bool(),
});
export type ActiveBardSong = __Infer<typeof ActiveBardSong>;

export const ActivePet = __t.object("ActivePet", {
  id: __t.u64(),
  characterId: __t.u64(),
  combatId: __t.option(__t.u64()),
  name: __t.string(),
  level: __t.u64(),
  currentHp: __t.u64(),
  maxHp: __t.u64(),
  attackDamage: __t.u64(),
  abilityKey: __t.option(__t.string()),
  nextAbilityAt: __t.option(__t.u64()),
  abilityCooldownSeconds: __t.option(__t.u64()),
  targetEnemyId: __t.option(__t.u64()),
  nextAutoAttackAt: __t.option(__t.u64()),
  expiresAtMicros: __t.option(__t.u64()),
});
export type ActivePet = __Infer<typeof ActivePet>;

export const AggroEntry = __t.object("AggroEntry", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyId: __t.u64(),
  characterId: __t.u64(),
  petId: __t.option(__t.u64()),
  value: __t.u64(),
});
export type AggroEntry = __Infer<typeof AggroEntry>;

export const AppVersion = __t.object("AppVersion", {
  id: __t.u64(),
  version: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AppVersion = __Infer<typeof AppVersion>;

export const BankSlot = __t.object("BankSlot", {
  id: __t.u64(),
  ownerUserId: __t.u64(),
  slot: __t.u64(),
  itemInstanceId: __t.u64(),
});
export type BankSlot = __Infer<typeof BankSlot>;

export const BardSongTick = __t.object("BardSongTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  bardCharacterId: __t.u64(),
  combatId: __t.option(__t.u64()),
});
export type BardSongTick = __Infer<typeof BardSongTick>;

export const CastTick = __t.object("CastTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CastTick = __Infer<typeof CastTick>;

export const Character = __t.object("Character", {
  id: __t.u64(),
  ownerUserId: __t.u64(),
  name: __t.string(),
  race: __t.string(),
  className: __t.string(),
  level: __t.u64(),
  xp: __t.u64(),
  gold: __t.u64(),
  locationId: __t.u64(),
  boundLocationId: __t.u64(),
  groupId: __t.option(__t.u64()),
  hp: __t.u64(),
  maxHp: __t.u64(),
  mana: __t.u64(),
  maxMana: __t.u64(),
  str: __t.u64(),
  dex: __t.u64(),
  cha: __t.u64(),
  wis: __t.u64(),
  int: __t.u64(),
  hitChance: __t.u64(),
  dodgeChance: __t.u64(),
  parryChance: __t.u64(),
  critMelee: __t.u64(),
  critRanged: __t.u64(),
  critDivine: __t.u64(),
  critArcane: __t.u64(),
  armorClass: __t.u64(),
  perception: __t.u64(),
  search: __t.u64(),
  ccPower: __t.u64(),
  vendorBuyMod: __t.u64(),
  vendorSellMod: __t.u64(),
  createdAt: __t.timestamp(),
  stamina: __t.u64(),
  maxStamina: __t.u64(),
  combatTargetEnemyId: __t.option(__t.u64()),
  racialSpellDamage: __t.option(__t.u64()),
  racialPhysDamage: __t.option(__t.u64()),
  racialMaxHp: __t.option(__t.u64()),
  racialMaxMana: __t.option(__t.u64()),
  racialManaRegen: __t.option(__t.u64()),
  racialStaminaRegen: __t.option(__t.u64()),
  racialCritBonus: __t.option(__t.u64()),
  racialArmorBonus: __t.option(__t.u64()),
  racialDodgeBonus: __t.option(__t.u64()),
  racialHpRegen: __t.option(__t.u64()),
  racialMaxStamina: __t.option(__t.u64()),
  racialTravelCostIncrease: __t.option(__t.u64()),
  racialTravelCostDiscount: __t.option(__t.u64()),
  racialHitBonus: __t.option(__t.u64()),
  racialParryBonus: __t.option(__t.u64()),
  racialFactionBonus: __t.option(__t.u64()),
  racialMagicResist: __t.option(__t.u64()),
  racialPerceptionBonus: __t.option(__t.u64()),
  racialLootBonus: __t.option(__t.u64()),
  lastCombatEndAt: __t.option(__t.u64()),
});
export type Character = __Infer<typeof Character>;

export const CharacterCast = __t.object("CharacterCast", {
  id: __t.u64(),
  characterId: __t.u64(),
  abilityKey: __t.string(),
  targetCharacterId: __t.option(__t.u64()),
  endsAtMicros: __t.u64(),
});
export type CharacterCast = __Infer<typeof CharacterCast>;

export const CharacterEffect = __t.object("CharacterEffect", {
  id: __t.u64(),
  characterId: __t.u64(),
  effectType: __t.string(),
  magnitude: __t.i64(),
  roundsRemaining: __t.u64(),
  sourceAbility: __t.option(__t.string()),
});
export type CharacterEffect = __Infer<typeof CharacterEffect>;

export const CharacterLogoutTick = __t.object("CharacterLogoutTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  characterId: __t.u64(),
  ownerUserId: __t.u64(),
  logoutAtMicros: __t.u64(),
});
export type CharacterLogoutTick = __Infer<typeof CharacterLogoutTick>;

export const CombatEncounter = __t.object("CombatEncounter", {
  id: __t.u64(),
  locationId: __t.u64(),
  groupId: __t.option(__t.u64()),
  leaderCharacterId: __t.option(__t.u64()),
  state: __t.string(),
  addCount: __t.u64(),
  pendingAddCount: __t.u64(),
  pendingAddAtMicros: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type CombatEncounter = __Infer<typeof CombatEncounter>;

export const CombatEnemy = __t.object("CombatEnemy", {
  id: __t.u64(),
  combatId: __t.u64(),
  spawnId: __t.u64(),
  enemyTemplateId: __t.u64(),
  enemyRoleTemplateId: __t.option(__t.u64()),
  displayName: __t.string(),
  currentHp: __t.u64(),
  maxHp: __t.u64(),
  attackDamage: __t.u64(),
  armorClass: __t.u64(),
  aggroTargetCharacterId: __t.option(__t.u64()),
  aggroTargetPetId: __t.option(__t.u64()),
  nextAutoAttackAt: __t.u64(),
});
export type CombatEnemy = __Infer<typeof CombatEnemy>;

export const CombatEnemyCast = __t.object("CombatEnemyCast", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyId: __t.u64(),
  abilityKey: __t.string(),
  endsAtMicros: __t.u64(),
  targetCharacterId: __t.option(__t.u64()),
  targetPetId: __t.option(__t.u64()),
});
export type CombatEnemyCast = __Infer<typeof CombatEnemyCast>;

export const CombatEnemyCooldown = __t.object("CombatEnemyCooldown", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyId: __t.u64(),
  abilityKey: __t.string(),
  readyAtMicros: __t.u64(),
});
export type CombatEnemyCooldown = __Infer<typeof CombatEnemyCooldown>;

export const CombatEnemyEffect = __t.object("CombatEnemyEffect", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyId: __t.u64(),
  effectType: __t.string(),
  magnitude: __t.i64(),
  roundsRemaining: __t.u64(),
  sourceAbility: __t.option(__t.string()),
  ownerCharacterId: __t.option(__t.u64()),
});
export type CombatEnemyEffect = __Infer<typeof CombatEnemyEffect>;

export const CombatLoopTick = __t.object("CombatLoopTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  combatId: __t.u64(),
});
export type CombatLoopTick = __Infer<typeof CombatLoopTick>;

export const CombatLoot = __t.object("CombatLoot", {
  id: __t.u64(),
  combatId: __t.u64(),
  ownerUserId: __t.u64(),
  characterId: __t.u64(),
  itemTemplateId: __t.u64(),
  createdAt: __t.timestamp(),
  qualityTier: __t.option(__t.string()),
  affixDataJson: __t.option(__t.string()),
  isNamed: __t.option(__t.bool()),
  craftQuality: __t.option(__t.string()),
});
export type CombatLoot = __Infer<typeof CombatLoot>;

export const CombatParticipant = __t.object("CombatParticipant", {
  id: __t.u64(),
  combatId: __t.u64(),
  characterId: __t.u64(),
  status: __t.string(),
  nextAutoAttackAt: __t.u64(),
});
export type CombatParticipant = __Infer<typeof CombatParticipant>;

export const CombatPendingAdd = __t.object("CombatPendingAdd", {
  id: __t.u64(),
  combatId: __t.u64(),
  enemyTemplateId: __t.u64(),
  enemyRoleTemplateId: __t.option(__t.u64()),
  spawnId: __t.option(__t.u64()),
  arriveAtMicros: __t.u64(),
});
export type CombatPendingAdd = __Infer<typeof CombatPendingAdd>;

export const CombatResult = __t.object("CombatResult", {
  id: __t.u64(),
  ownerUserId: __t.u64(),
  characterId: __t.u64(),
  groupId: __t.option(__t.u64()),
  combatId: __t.u64(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type CombatResult = __Infer<typeof CombatResult>;

export const Command = __t.object("Command", {
  id: __t.u64(),
  ownerUserId: __t.u64(),
  characterId: __t.u64(),
  text: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Command = __Infer<typeof Command>;

export const Corpse = __t.object("Corpse", {
  id: __t.u64(),
  characterId: __t.u64(),
  locationId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Corpse = __Infer<typeof Corpse>;

export const CorpseItem = __t.object("CorpseItem", {
  id: __t.u64(),
  corpseId: __t.u64(),
  itemInstanceId: __t.u64(),
});
export type CorpseItem = __Infer<typeof CorpseItem>;

export const DayNightTick = __t.object("DayNightTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DayNightTick = __Infer<typeof DayNightTick>;

export const DisconnectLogoutTick = __t.object("DisconnectLogoutTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  playerId: __t.identity(),
  disconnectAtMicros: __t.u64(),
});
export type DisconnectLogoutTick = __Infer<typeof DisconnectLogoutTick>;

export const EffectTick = __t.object("EffectTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EffectTick = __Infer<typeof EffectTick>;

export const EnemyAbility = __t.object("EnemyAbility", {
  id: __t.u64(),
  enemyTemplateId: __t.u64(),
  abilityKey: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  castSeconds: __t.u64(),
  cooldownSeconds: __t.u64(),
  targetRule: __t.string(),
});
export type EnemyAbility = __Infer<typeof EnemyAbility>;

export const EnemyRespawnTick = __t.object("EnemyRespawnTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  locationId: __t.u64(),
});
export type EnemyRespawnTick = __Infer<typeof EnemyRespawnTick>;

export const EnemyRoleTemplate = __t.object("EnemyRoleTemplate", {
  id: __t.u64(),
  enemyTemplateId: __t.u64(),
  roleKey: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  roleDetail: __t.string(),
  abilityProfile: __t.string(),
});
export type EnemyRoleTemplate = __Infer<typeof EnemyRoleTemplate>;

export const EnemySpawn = __t.object("EnemySpawn", {
  id: __t.u64(),
  locationId: __t.u64(),
  enemyTemplateId: __t.u64(),
  name: __t.string(),
  state: __t.string(),
  lockedCombatId: __t.option(__t.u64()),
  groupCount: __t.u64(),
});
export type EnemySpawn = __Infer<typeof EnemySpawn>;

export const EnemySpawnMember = __t.object("EnemySpawnMember", {
  id: __t.u64(),
  spawnId: __t.u64(),
  enemyTemplateId: __t.u64(),
  roleTemplateId: __t.u64(),
});
export type EnemySpawnMember = __Infer<typeof EnemySpawnMember>;

export const EnemyTemplate = __t.object("EnemyTemplate", {
  id: __t.u64(),
  name: __t.string(),
  role: __t.string(),
  roleDetail: __t.string(),
  abilityProfile: __t.string(),
  terrainTypes: __t.string(),
  creatureType: __t.string(),
  timeOfDay: __t.string(),
  socialGroup: __t.string(),
  socialRadius: __t.u64(),
  awareness: __t.string(),
  groupMin: __t.u64(),
  groupMax: __t.u64(),
  armorClass: __t.u64(),
  level: __t.u64(),
  maxHp: __t.u64(),
  baseDamage: __t.u64(),
  xpReward: __t.u64(),
  factionId: __t.option(__t.u64()),
  isBoss: __t.option(__t.bool()),
  isSocial: __t.option(__t.bool()),
  bossRegionName: __t.option(__t.string()),
});
export type EnemyTemplate = __Infer<typeof EnemyTemplate>;

export const EventContribution = __t.object("EventContribution", {
  id: __t.u64(),
  eventId: __t.u64(),
  characterId: __t.u64(),
  count: __t.u64(),
  regionEnteredAt: __t.timestamp(),
});
export type EventContribution = __Infer<typeof EventContribution>;

export const EventDespawnTick = __t.object("EventDespawnTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  eventId: __t.u64(),
});
export type EventDespawnTick = __Infer<typeof EventDespawnTick>;

export const EventGroup = __t.object("EventGroup", {
  id: __t.u64(),
  groupId: __t.u64(),
  characterId: __t.u64(),
  message: __t.string(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
});
export type EventGroup = __Infer<typeof EventGroup>;

export const EventLocation = __t.object("EventLocation", {
  id: __t.u64(),
  locationId: __t.u64(),
  message: __t.string(),
  kind: __t.string(),
  excludeCharacterId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type EventLocation = __Infer<typeof EventLocation>;

export const EventObjective = __t.object("EventObjective", {
  id: __t.u64(),
  eventId: __t.u64(),
  objectiveType: __t.string(),
  locationId: __t.u64(),
  name: __t.string(),
  targetCount: __t.u64(),
  currentCount: __t.u64(),
  isAlive: __t.option(__t.bool()),
});
export type EventObjective = __Infer<typeof EventObjective>;

export const EventPrivate = __t.object("EventPrivate", {
  id: __t.u64(),
  ownerUserId: __t.u64(),
  characterId: __t.u64(),
  message: __t.string(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
});
export type EventPrivate = __Infer<typeof EventPrivate>;

export const EventSpawnEnemy = __t.object("EventSpawnEnemy", {
  id: __t.u64(),
  eventId: __t.u64(),
  spawnId: __t.u64(),
  locationId: __t.u64(),
});
export type EventSpawnEnemy = __Infer<typeof EventSpawnEnemy>;

export const EventSpawnItem = __t.object("EventSpawnItem", {
  id: __t.u64(),
  eventId: __t.u64(),
  locationId: __t.u64(),
  name: __t.string(),
  collected: __t.bool(),
  collectedByCharacterId: __t.option(__t.u64()),
});
export type EventSpawnItem = __Infer<typeof EventSpawnItem>;

export const EventWorld = __t.object("EventWorld", {
  id: __t.u64(),
  message: __t.string(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
});
export type EventWorld = __Infer<typeof EventWorld>;

export const Faction = __t.object("Faction", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  rivalFactionId: __t.option(__t.u64()),
});
export type Faction = __Infer<typeof Faction>;

export const FactionStanding = __t.object("FactionStanding", {
  id: __t.u64(),
  characterId: __t.u64(),
  factionId: __t.u64(),
  standing: __t.i64(),
});
export type FactionStanding = __Infer<typeof FactionStanding>;

export const Friend = __t.object("Friend", {
  id: __t.u64(),
  userId: __t.u64(),
  friendUserId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Friend = __Infer<typeof Friend>;

export const FriendRequest = __t.object("FriendRequest", {
  id: __t.u64(),
  fromUserId: __t.u64(),
  toUserId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const Group = __t.object("Group", {
  id: __t.u64(),
  name: __t.string(),
  leaderCharacterId: __t.u64(),
  pullerCharacterId: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type Group = __Infer<typeof Group>;

export const GroupInvite = __t.object("GroupInvite", {
  id: __t.u64(),
  groupId: __t.u64(),
  fromCharacterId: __t.u64(),
  toCharacterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type GroupInvite = __Infer<typeof GroupInvite>;

export const GroupMember = __t.object("GroupMember", {
  id: __t.u64(),
  groupId: __t.u64(),
  characterId: __t.u64(),
  ownerUserId: __t.u64(),
  role: __t.string(),
  followLeader: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type GroupMember = __Infer<typeof GroupMember>;

export const HealthRegenTick = __t.object("HealthRegenTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HealthRegenTick = __Infer<typeof HealthRegenTick>;

export const HotTick = __t.object("HotTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HotTick = __Infer<typeof HotTick>;

export const HotbarSlot = __t.object("HotbarSlot", {
  id: __t.u64(),
  characterId: __t.u64(),
  slot: __t.u8(),
  abilityKey: __t.string(),
  assignedAt: __t.timestamp(),
});
export type HotbarSlot = __Infer<typeof HotbarSlot>;

export const InactivityTick = __t.object("InactivityTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type InactivityTick = __Infer<typeof InactivityTick>;

export const ItemAffix = __t.object("ItemAffix", {
  id: __t.u64(),
  itemInstanceId: __t.u64(),
  affixType: __t.string(),
  affixKey: __t.string(),
  affixName: __t.string(),
  statKey: __t.string(),
  magnitude: __t.i64(),
});
export type ItemAffix = __Infer<typeof ItemAffix>;

export const ItemCooldown = __t.object("ItemCooldown", {
  id: __t.u64(),
  characterId: __t.u64(),
  itemKey: __t.string(),
  readyAtMicros: __t.u64(),
});
export type ItemCooldown = __Infer<typeof ItemCooldown>;

export const ItemInstance = __t.object("ItemInstance", {
  id: __t.u64(),
  templateId: __t.u64(),
  ownerCharacterId: __t.u64(),
  equippedSlot: __t.option(__t.string()),
  quantity: __t.u64(),
  qualityTier: __t.option(__t.string()),
  craftQuality: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  isNamed: __t.option(__t.bool()),
  isTemporary: __t.option(__t.bool()),
});
export type ItemInstance = __Infer<typeof ItemInstance>;

export const ItemTemplate = __t.object("ItemTemplate", {
  id: __t.u64(),
  name: __t.string(),
  slot: __t.string(),
  armorType: __t.string(),
  rarity: __t.string(),
  tier: __t.u64(),
  isJunk: __t.bool(),
  vendorValue: __t.u64(),
  requiredLevel: __t.u64(),
  allowedClasses: __t.string(),
  strBonus: __t.u64(),
  dexBonus: __t.u64(),
  chaBonus: __t.u64(),
  wisBonus: __t.u64(),
  intBonus: __t.u64(),
  hpBonus: __t.u64(),
  manaBonus: __t.u64(),
  armorClassBonus: __t.u64(),
  magicResistanceBonus: __t.u64(),
  weaponBaseDamage: __t.u64(),
  weaponDps: __t.u64(),
  weaponType: __t.string(),
  stackable: __t.bool(),
  wellFedDurationMicros: __t.u64(),
  wellFedBuffType: __t.string(),
  wellFedBuffMagnitude: __t.u64(),
  description: __t.option(__t.string()),
});
export type ItemTemplate = __Infer<typeof ItemTemplate>;

export const Location = __t.object("Location", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  zone: __t.string(),
  regionId: __t.u64(),
  levelOffset: __t.i64(),
  isSafe: __t.bool(),
  terrainType: __t.string(),
  bindStone: __t.bool(),
  craftingAvailable: __t.bool(),
});
export type Location = __Infer<typeof Location>;

export const LocationConnection = __t.object("LocationConnection", {
  id: __t.u64(),
  fromLocationId: __t.u64(),
  toLocationId: __t.u64(),
});
export type LocationConnection = __Infer<typeof LocationConnection>;

export const LocationEnemyTemplate = __t.object("LocationEnemyTemplate", {
  id: __t.u64(),
  locationId: __t.u64(),
  enemyTemplateId: __t.u64(),
});
export type LocationEnemyTemplate = __Infer<typeof LocationEnemyTemplate>;

export const LootTable = __t.object("LootTable", {
  id: __t.u64(),
  terrainType: __t.string(),
  creatureType: __t.string(),
  tier: __t.u64(),
  junkChance: __t.u64(),
  gearChance: __t.u64(),
  goldMin: __t.u64(),
  goldMax: __t.u64(),
});
export type LootTable = __Infer<typeof LootTable>;

export const LootTableEntry = __t.object("LootTableEntry", {
  id: __t.u64(),
  lootTableId: __t.u64(),
  itemTemplateId: __t.u64(),
  weight: __t.u64(),
});
export type LootTableEntry = __Infer<typeof LootTableEntry>;

export const MyBankSlots = __t.object("MyBankSlots", {});
export type MyBankSlots = __Infer<typeof MyBankSlots>;

export const MyCharacterEffects = __t.object("MyCharacterEffects", {});
export type MyCharacterEffects = __Infer<typeof MyCharacterEffects>;

export const MyCombatLoot = __t.object("MyCombatLoot", {});
export type MyCombatLoot = __Infer<typeof MyCombatLoot>;

export const MyCombatResults = __t.object("MyCombatResults", {});
export type MyCombatResults = __Infer<typeof MyCombatResults>;

export const MyFactionStandings = __t.object("MyFactionStandings", {});
export type MyFactionStandings = __Infer<typeof MyFactionStandings>;

export const MyFriendRequests = __t.object("MyFriendRequests", {});
export type MyFriendRequests = __Infer<typeof MyFriendRequests>;

export const MyFriends = __t.object("MyFriends", {});
export type MyFriends = __Infer<typeof MyFriends>;

export const MyGroupEvents = __t.object("MyGroupEvents", {});
export type MyGroupEvents = __Infer<typeof MyGroupEvents>;

export const MyGroupInvites = __t.object("MyGroupInvites", {});
export type MyGroupInvites = __Infer<typeof MyGroupInvites>;

export const MyGroupMembers = __t.object("MyGroupMembers", {});
export type MyGroupMembers = __Infer<typeof MyGroupMembers>;

export const MyNpcDialog = __t.object("MyNpcDialog", {});
export type MyNpcDialog = __Infer<typeof MyNpcDialog>;

export const MyPanelLayout = __t.object("MyPanelLayout", {});
export type MyPanelLayout = __Infer<typeof MyPanelLayout>;

export const MyPlayer = __t.object("MyPlayer", {});
export type MyPlayer = __Infer<typeof MyPlayer>;

export const MyQuests = __t.object("MyQuests", {});
export type MyQuests = __Infer<typeof MyQuests>;

export const NamedEnemy = __t.object("NamedEnemy", {
  id: __t.u64(),
  characterId: __t.u64(),
  name: __t.string(),
  enemyTemplateId: __t.u64(),
  locationId: __t.u64(),
  isAlive: __t.bool(),
  lastKilledAt: __t.option(__t.timestamp()),
  respawnMinutes: __t.u64(),
});
export type NamedEnemy = __Infer<typeof NamedEnemy>;

export const Npc = __t.object("Npc", {
  id: __t.u64(),
  name: __t.string(),
  npcType: __t.string(),
  locationId: __t.u64(),
  description: __t.string(),
  greeting: __t.string(),
  factionId: __t.option(__t.u64()),
  personalityJson: __t.option(__t.string()),
  baseMood: __t.option(__t.string()),
});
export type Npc = __Infer<typeof Npc>;

export const NpcAffinity = __t.object("NpcAffinity", {
  id: __t.u64(),
  characterId: __t.u64(),
  npcId: __t.u64(),
  affinity: __t.i64(),
  lastInteraction: __t.timestamp(),
  giftsGiven: __t.u64(),
  conversationCount: __t.u64(),
  hasGreeted: __t.option(__t.bool()),
});
export type NpcAffinity = __Infer<typeof NpcAffinity>;

export const NpcDialog = __t.object("NpcDialog", {
  id: __t.u64(),
  characterId: __t.u64(),
  npcId: __t.u64(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type NpcDialog = __Infer<typeof NpcDialog>;

export const NpcDialogueOption = __t.object("NpcDialogueOption", {
  id: __t.u64(),
  npcId: __t.u64(),
  parentOptionId: __t.option(__t.u64()),
  optionKey: __t.string(),
  playerText: __t.string(),
  npcResponse: __t.string(),
  requiredAffinity: __t.i64(),
  requiredFactionId: __t.option(__t.u64()),
  requiredFactionStanding: __t.option(__t.i64()),
  requiredRenownRank: __t.option(__t.u64()),
  affinityChange: __t.i64(),
  sortOrder: __t.u64(),
  questTemplateName: __t.option(__t.string()),
  affinityHint: __t.option(__t.string()),
  isAffinityLocked: __t.option(__t.bool()),
});
export type NpcDialogueOption = __Infer<typeof NpcDialogueOption>;

export const NpcDialogueVisited = __t.object("NpcDialogueVisited", {
  id: __t.u64(),
  characterId: __t.u64(),
  npcId: __t.u64(),
  dialogueOptionId: __t.u64(),
  visitedAt: __t.timestamp(),
});
export type NpcDialogueVisited = __Infer<typeof NpcDialogueVisited>;

export const PendingSpellCast = __t.object("PendingSpellCast", {
  id: __t.u64(),
  spellType: __t.string(),
  casterCharacterId: __t.u64(),
  targetCharacterId: __t.u64(),
  corpseId: __t.option(__t.u64()),
  createdAtMicros: __t.u64(),
});
export type PendingSpellCast = __Infer<typeof PendingSpellCast>;

export const Player = __t.object("Player", {
  id: __t.identity(),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  displayName: __t.option(__t.string()),
  activeCharacterId: __t.option(__t.u64()),
  userId: __t.option(__t.u64()),
  sessionStartedAt: __t.option(__t.timestamp()),
  lastActivityAt: __t.option(__t.timestamp()),
});
export type Player = __Infer<typeof Player>;

export const PullState = __t.object("PullState", {
  id: __t.u64(),
  characterId: __t.u64(),
  groupId: __t.option(__t.u64()),
  locationId: __t.u64(),
  enemySpawnId: __t.u64(),
  pullType: __t.string(),
  state: __t.string(),
  outcome: __t.option(__t.string()),
  delayedAdds: __t.option(__t.u64()),
  delayedAddsAtMicros: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type PullState = __Infer<typeof PullState>;

export const PullTick = __t.object("PullTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  pullId: __t.u64(),
});
export type PullTick = __Infer<typeof PullTick>;

export const QuestInstance = __t.object("QuestInstance", {
  id: __t.u64(),
  characterId: __t.u64(),
  questTemplateId: __t.u64(),
  progress: __t.u64(),
  completed: __t.bool(),
  acceptedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type QuestInstance = __Infer<typeof QuestInstance>;

export const QuestItem = __t.object("QuestItem", {
  id: __t.u64(),
  characterId: __t.u64(),
  questTemplateId: __t.u64(),
  locationId: __t.u64(),
  name: __t.string(),
  discovered: __t.bool(),
  looted: __t.bool(),
});
export type QuestItem = __Infer<typeof QuestItem>;

export const QuestTemplate = __t.object("QuestTemplate", {
  id: __t.u64(),
  name: __t.string(),
  npcId: __t.u64(),
  targetEnemyTemplateId: __t.u64(),
  requiredCount: __t.u64(),
  minLevel: __t.u64(),
  maxLevel: __t.u64(),
  rewardXp: __t.u64(),
  questType: __t.option(__t.string()),
  targetLocationId: __t.option(__t.u64()),
  targetNpcId: __t.option(__t.u64()),
  targetItemName: __t.option(__t.string()),
  itemDropChance: __t.option(__t.u64()),
});
export type QuestTemplate = __Infer<typeof QuestTemplate>;

export const Race = __t.object("Race", {
  id: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  availableClasses: __t.string(),
  bonus1Type: __t.string(),
  bonus1Value: __t.u64(),
  bonus2Type: __t.string(),
  bonus2Value: __t.u64(),
  penaltyType: __t.option(__t.string()),
  penaltyValue: __t.option(__t.u64()),
  levelBonusType: __t.string(),
  levelBonusValue: __t.u64(),
  unlocked: __t.bool(),
});
export type Race = __Infer<typeof Race>;

export const RecipeDiscovered = __t.object("RecipeDiscovered", {
  id: __t.u64(),
  characterId: __t.u64(),
  recipeTemplateId: __t.u64(),
  discoveredAt: __t.timestamp(),
});
export type RecipeDiscovered = __Infer<typeof RecipeDiscovered>;

export const RecipeTemplate = __t.object("RecipeTemplate", {
  id: __t.u64(),
  key: __t.string(),
  name: __t.string(),
  outputTemplateId: __t.u64(),
  outputCount: __t.u64(),
  req1TemplateId: __t.u64(),
  req1Count: __t.u64(),
  req2TemplateId: __t.u64(),
  req2Count: __t.u64(),
  req3TemplateId: __t.option(__t.u64()),
  req3Count: __t.option(__t.u64()),
  recipeType: __t.option(__t.string()),
  materialType: __t.option(__t.string()),
});
export type RecipeTemplate = __Infer<typeof RecipeTemplate>;

export const Region = __t.object("Region", {
  id: __t.u64(),
  name: __t.string(),
  dangerMultiplier: __t.u64(),
  regionType: __t.string(),
});
export type Region = __Infer<typeof Region>;

export const Renown = __t.object("Renown", {
  id: __t.u64(),
  characterId: __t.u64(),
  points: __t.u64(),
  currentRank: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Renown = __Infer<typeof Renown>;

export const RenownPerk = __t.object("RenownPerk", {
  id: __t.u64(),
  characterId: __t.u64(),
  rank: __t.u64(),
  perkKey: __t.string(),
  chosenAt: __t.timestamp(),
});
export type RenownPerk = __Infer<typeof RenownPerk>;

export const RenownServerFirst = __t.object("RenownServerFirst", {
  id: __t.u64(),
  category: __t.string(),
  achievementKey: __t.string(),
  characterId: __t.u64(),
  characterName: __t.string(),
  achievedAt: __t.timestamp(),
  position: __t.u64(),
});
export type RenownServerFirst = __Infer<typeof RenownServerFirst>;

export const ResourceGather = __t.object("ResourceGather", {
  id: __t.u64(),
  characterId: __t.u64(),
  nodeId: __t.u64(),
  endsAtMicros: __t.u64(),
});
export type ResourceGather = __Infer<typeof ResourceGather>;

export const ResourceGatherTick = __t.object("ResourceGatherTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gatherId: __t.u64(),
});
export type ResourceGatherTick = __Infer<typeof ResourceGatherTick>;

export const ResourceNode = __t.object("ResourceNode", {
  id: __t.u64(),
  locationId: __t.u64(),
  characterId: __t.option(__t.u64()),
  itemTemplateId: __t.u64(),
  name: __t.string(),
  timeOfDay: __t.string(),
  quantity: __t.u64(),
  state: __t.string(),
  lockedByCharacterId: __t.option(__t.u64()),
  respawnAtMicros: __t.option(__t.u64()),
});
export type ResourceNode = __Infer<typeof ResourceNode>;

export const SearchResult = __t.object("SearchResult", {
  id: __t.u64(),
  characterId: __t.u64(),
  locationId: __t.u64(),
  foundResources: __t.bool(),
  foundQuestItem: __t.bool(),
  questItemId: __t.option(__t.u64()),
  foundNamedEnemy: __t.bool(),
  namedEnemyId: __t.option(__t.u64()),
  searchedAt: __t.timestamp(),
});
export type SearchResult = __Infer<typeof SearchResult>;

export const TradeItem = __t.object("TradeItem", {
  id: __t.u64(),
  tradeId: __t.u64(),
  fromCharacterId: __t.u64(),
  itemInstanceId: __t.u64(),
  quantity: __t.u64(),
});
export type TradeItem = __Infer<typeof TradeItem>;

export const TradeSession = __t.object("TradeSession", {
  id: __t.u64(),
  fromCharacterId: __t.u64(),
  toCharacterId: __t.u64(),
  state: __t.string(),
  fromAccepted: __t.bool(),
  toAccepted: __t.bool(),
  createdAt: __t.timestamp(),
});
export type TradeSession = __Infer<typeof TradeSession>;

export const TravelCooldown = __t.object("TravelCooldown", {
  id: __t.u64(),
  characterId: __t.u64(),
  readyAtMicros: __t.u64(),
});
export type TravelCooldown = __Infer<typeof TravelCooldown>;

export const UiPanelLayout = __t.object("UiPanelLayout", {
  id: __t.u64(),
  characterId: __t.u64(),
  panelStatesJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UiPanelLayout = __Infer<typeof UiPanelLayout>;

export const User = __t.object("User", {
  id: __t.u64(),
  email: __t.string(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const VendorInventory = __t.object("VendorInventory", {
  id: __t.u64(),
  npcId: __t.u64(),
  itemTemplateId: __t.u64(),
  price: __t.u64(),
  qualityTier: __t.option(__t.string()),
});
export type VendorInventory = __Infer<typeof VendorInventory>;

export const WorldEvent = __t.object("WorldEvent", {
  id: __t.u64(),
  eventKey: __t.string(),
  name: __t.string(),
  regionId: __t.u64(),
  status: __t.string(),
  isRecurring: __t.bool(),
  firedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  failureConditionType: __t.string(),
  deadlineAtMicros: __t.u64(),
  successThreshold: __t.u64(),
  failureThreshold: __t.u64(),
  successCounter: __t.u64(),
  failureCounter: __t.u64(),
  successConsequenceType: __t.string(),
  successConsequencePayload: __t.string(),
  failureConsequenceType: __t.string(),
  failureConsequencePayload: __t.string(),
  rewardTiersJson: __t.string(),
  consequenceText: __t.option(__t.string()),
});
export type WorldEvent = __Infer<typeof WorldEvent>;

export const WorldStatTracker = __t.object("WorldStatTracker", {
  id: __t.u64(),
  statKey: __t.string(),
  currentValue: __t.u64(),
  fireThreshold: __t.u64(),
  eventKeyToFire: __t.string(),
  fired: __t.bool(),
});
export type WorldStatTracker = __Infer<typeof WorldStatTracker>;

export const WorldState = __t.object("WorldState", {
  id: __t.u64(),
  startingLocationId: __t.u64(),
  isNight: __t.bool(),
  nextTransitionAtMicros: __t.u64(),
});
export type WorldState = __Infer<typeof WorldState>;

