// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("WorldStatTracker", {
  id: __t.u64(),
  statKey: __t.string(),
  currentValue: __t.u64(),
  fireThreshold: __t.u64(),
  eventKeyToFire: __t.string(),
  fired: __t.bool(),
});


