// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventKey: __t.string(),
  name: __t.string(),
  regionId: __t.u64(),
  status: __t.string(),
  isRecurring: __t.bool(),
  firedAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
  failureConditionType: __t.string(),
  deadlineAtMicros: __t.option(__t.u64()),
  successThreshold: __t.option(__t.u64()),
  failureThreshold: __t.option(__t.u64()),
  successCounter: __t.option(__t.u64()),
  failureCounter: __t.option(__t.u64()),
  successConsequenceType: __t.string(),
  successConsequencePayload: __t.string(),
  failureConsequenceType: __t.string(),
  failureConsequencePayload: __t.string(),
  rewardTiersJson: __t.string(),
  consequenceText: __t.option(__t.string()),
});
