// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventKey: __t.string().name("event_key"),
  name: __t.string(),
  regionId: __t.u64().name("region_id"),
  status: __t.string(),
  isRecurring: __t.bool().name("is_recurring"),
  firedAt: __t.timestamp().name("fired_at"),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  failureConditionType: __t.string().name("failure_condition_type"),
  deadlineAtMicros: __t.u64().name("deadline_at_micros"),
  successThreshold: __t.u64().name("success_threshold"),
  failureThreshold: __t.u64().name("failure_threshold"),
  successCounter: __t.u64().name("success_counter"),
  failureCounter: __t.u64().name("failure_counter"),
  successConsequenceType: __t.string().name("success_consequence_type"),
  successConsequencePayload: __t.string().name("success_consequence_payload"),
  failureConsequenceType: __t.string().name("failure_consequence_type"),
  failureConsequencePayload: __t.string().name("failure_consequence_payload"),
  rewardTiersJson: __t.string().name("reward_tiers_json"),
  consequenceText: __t.option(__t.string()).name("consequence_text"),
});
