// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.identity().name("player_id"),
  characterId: __t.u64().name("character_id"),
  sourceLocationId: __t.u64().name("source_location_id"),
  sourceRegionId: __t.u64().name("source_region_id"),
  step: __t.string(),
  generatedRegionId: __t.option(__t.u64()).name("generated_region_id"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
