// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.8.0 (commit 549f84c80846137ec1ef7468d01673a329c0501f).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CreateAccount } from "./create_account_reducer.ts";
export { CreateAccount };
import { UpsertAccount } from "./upsert_account_reducer.ts";
export { UpsertAccount };
import { CreateOrUpdateSession } from "./create_or_update_session_reducer.ts";
export { CreateOrUpdateSession };
import { TouchSession } from "./touch_session_reducer.ts";
export { TouchSession };

// Import and reexport all table handle types
import { AccountsTableHandle } from "./accounts_table.ts";
export { AccountsTableHandle };
import { SessionsTableHandle } from "./sessions_table.ts";
export { SessionsTableHandle };

// Import and reexport all types
import { Accounts } from "./accounts_type.ts";
export { Accounts };
import { Sessions } from "./sessions_type.ts";
export { Sessions };

const REMOTE_MODULE = {
  tables: {
    accounts: {
      tableName: "accounts" as const,
      rowType: Accounts.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Accounts.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    sessions: {
      tableName: "sessions" as const,
      rowType: Sessions.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Sessions.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    create_account: {
      reducerName: "create_account",
      argsType: CreateAccount.getTypeScriptAlgebraicType(),
    },
    upsert_account: {
      reducerName: "upsert_account",
      argsType: UpsertAccount.getTypeScriptAlgebraicType(),
    },
    create_or_update_session: {
      reducerName: "create_or_update_session",
      argsType: CreateOrUpdateSession.getTypeScriptAlgebraicType(),
    },
    touch_session: {
      reducerName: "touch_session",
      argsType: TouchSession.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.8.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CreateAccount", args: CreateAccount }
| { name: "UpsertAccount", args: UpsertAccount }
| { name: "CreateOrUpdateSession", args: CreateOrUpdateSession }
| { name: "TouchSession", args: TouchSession }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  createAccount(provider: string, providerUserId: string, displayName: string | undefined) {
    const __args = { provider, providerUserId, displayName };
    let __writer = new __BinaryWriter(1024);
    CreateAccount.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_account", __argsBuffer, this.setCallReducerFlags.createAccountFlags);
  }

  onCreateAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.onReducer("create_account", callback);
  }

  removeOnCreateAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.offReducer("create_account", callback);
  }

  upsertAccount(provider: string, providerUserId: string, displayName: string | undefined) {
    const __args = { provider, providerUserId, displayName };
    let __writer = new __BinaryWriter(1024);
    UpsertAccount.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("upsert_account", __argsBuffer, this.setCallReducerFlags.upsertAccountFlags);
  }

  onUpsertAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.onReducer("upsert_account", callback);
  }

  removeOnUpsertAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.offReducer("upsert_account", callback);
  }

  createOrUpdateSession(providerUserId: string, sessionToken: string, ttlMinutes: number) {
    const __args = { providerUserId, sessionToken, ttlMinutes };
    let __writer = new __BinaryWriter(1024);
    CreateOrUpdateSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_or_update_session", __argsBuffer, this.setCallReducerFlags.createOrUpdateSessionFlags);
  }

  onCreateOrUpdateSession(callback: (ctx: ReducerEventContext, providerUserId: string, sessionToken: string, ttlMinutes: number) => void) {
    this.connection.onReducer("create_or_update_session", callback);
  }

  removeOnCreateOrUpdateSession(callback: (ctx: ReducerEventContext, providerUserId: string, sessionToken: string, ttlMinutes: number) => void) {
    this.connection.offReducer("create_or_update_session", callback);
  }

  touchSession(sessionToken: string) {
    const __args = { sessionToken };
    let __writer = new __BinaryWriter(1024);
    TouchSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("touch_session", __argsBuffer, this.setCallReducerFlags.touchSessionFlags);
  }

  onTouchSession(callback: (ctx: ReducerEventContext, sessionToken: string) => void) {
    this.connection.onReducer("touch_session", callback);
  }

  removeOnTouchSession(callback: (ctx: ReducerEventContext, sessionToken: string) => void) {
    this.connection.offReducer("touch_session", callback);
  }

}

export class SetReducerFlags {
  createAccountFlags: __CallReducerFlags = 'FullUpdate';
  createAccount(flags: __CallReducerFlags) {
    this.createAccountFlags = flags;
  }

  upsertAccountFlags: __CallReducerFlags = 'FullUpdate';
  upsertAccount(flags: __CallReducerFlags) {
    this.upsertAccountFlags = flags;
  }

  createOrUpdateSessionFlags: __CallReducerFlags = 'FullUpdate';
  createOrUpdateSession(flags: __CallReducerFlags) {
    this.createOrUpdateSessionFlags = flags;
  }

  touchSessionFlags: __CallReducerFlags = 'FullUpdate';
  touchSession(flags: __CallReducerFlags) {
    this.touchSessionFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get accounts(): AccountsTableHandle<'accounts'> {
    // clientCache is a private property
    return new AccountsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Accounts>(REMOTE_MODULE.tables.accounts));
  }

  get sessions(): SessionsTableHandle<'sessions'> {
    // clientCache is a private property
    return new SessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Sessions>(REMOTE_MODULE.tables.sessions));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
