// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.8.0 (commit 549f84c80846137ec1ef7468d01673a329c0501f).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CreateAccount } from "./create_account_reducer.ts";
export { CreateAccount };
import { UpsertAccount } from "./upsert_account_reducer.ts";
export { UpsertAccount };
import { CreateOrUpdateSession } from "./create_or_update_session_reducer.ts";
export { CreateOrUpdateSession };
import { TouchSession } from "./touch_session_reducer.ts";
export { TouchSession };
import { CreateCharacter } from "./create_character_reducer.ts";
export { CreateCharacter };
import { UpdateCharacter } from "./update_character_reducer.ts";
export { UpdateCharacter };
import { DeleteCharacter } from "./delete_character_reducer.ts";
export { DeleteCharacter };
import { SetActiveCharacter } from "./set_active_character_reducer.ts";
export { SetActiveCharacter };
import { SaveCharacterDraft } from "./save_character_draft_reducer.ts";
export { SaveCharacterDraft };
import { DeleteCharacterDraft } from "./delete_character_draft_reducer.ts";
export { DeleteCharacterDraft };
import { FinalizeCharacterDraft } from "./finalize_character_draft_reducer.ts";
export { FinalizeCharacterDraft };

// Import and reexport all table handle types
import { AccountsTableHandle } from "./accounts_table.ts";
export { AccountsTableHandle };
import { CharacterDraftsTableHandle } from "./character_drafts_table.ts";
export { CharacterDraftsTableHandle };
import { CharactersTableHandle } from "./characters_table.ts";
export { CharactersTableHandle };
import { SessionsTableHandle } from "./sessions_table.ts";
export { SessionsTableHandle };

// Import and reexport all types
import { UpdatePatch } from "./update_patch_type.ts";
export { UpdatePatch };
import { Accounts } from "./accounts_type.ts";
export { Accounts };
import { CharacterDrafts } from "./character_drafts_type.ts";
export { CharacterDrafts };
import { Characters } from "./characters_type.ts";
export { Characters };
import { Sessions } from "./sessions_type.ts";
export { Sessions };

const REMOTE_MODULE = {
  tables: {
    accounts: {
      tableName: "accounts" as const,
      rowType: Accounts.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Accounts.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    character_drafts: {
      tableName: "character_drafts" as const,
      rowType: CharacterDrafts.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (CharacterDrafts.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    characters: {
      tableName: "characters" as const,
      rowType: Characters.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Characters.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    sessions: {
      tableName: "sessions" as const,
      rowType: Sessions.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Sessions.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    create_account: {
      reducerName: "create_account",
      argsType: CreateAccount.getTypeScriptAlgebraicType(),
    },
    upsert_account: {
      reducerName: "upsert_account",
      argsType: UpsertAccount.getTypeScriptAlgebraicType(),
    },
    create_or_update_session: {
      reducerName: "create_or_update_session",
      argsType: CreateOrUpdateSession.getTypeScriptAlgebraicType(),
    },
    touch_session: {
      reducerName: "touch_session",
      argsType: TouchSession.getTypeScriptAlgebraicType(),
    },
    create_character: {
      reducerName: "create_character",
      argsType: CreateCharacter.getTypeScriptAlgebraicType(),
    },
    update_character: {
      reducerName: "update_character",
      argsType: UpdateCharacter.getTypeScriptAlgebraicType(),
    },
    delete_character: {
      reducerName: "delete_character",
      argsType: DeleteCharacter.getTypeScriptAlgebraicType(),
    },
    set_active_character: {
      reducerName: "set_active_character",
      argsType: SetActiveCharacter.getTypeScriptAlgebraicType(),
    },
    save_character_draft: {
      reducerName: "save_character_draft",
      argsType: SaveCharacterDraft.getTypeScriptAlgebraicType(),
    },
    delete_character_draft: {
      reducerName: "delete_character_draft",
      argsType: DeleteCharacterDraft.getTypeScriptAlgebraicType(),
    },
    finalize_character_draft: {
      reducerName: "finalize_character_draft",
      argsType: FinalizeCharacterDraft.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.8.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CreateAccount", args: CreateAccount }
| { name: "UpsertAccount", args: UpsertAccount }
| { name: "CreateOrUpdateSession", args: CreateOrUpdateSession }
| { name: "TouchSession", args: TouchSession }
| { name: "CreateCharacter", args: CreateCharacter }
| { name: "UpdateCharacter", args: UpdateCharacter }
| { name: "DeleteCharacter", args: DeleteCharacter }
| { name: "SetActiveCharacter", args: SetActiveCharacter }
| { name: "SaveCharacterDraft", args: SaveCharacterDraft }
| { name: "DeleteCharacterDraft", args: DeleteCharacterDraft }
| { name: "FinalizeCharacterDraft", args: FinalizeCharacterDraft }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  createAccount(provider: string, providerUserId: string, displayName: string | undefined) {
    const __args = { provider, providerUserId, displayName };
    let __writer = new __BinaryWriter(1024);
    CreateAccount.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_account", __argsBuffer, this.setCallReducerFlags.createAccountFlags);
  }

  onCreateAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.onReducer("create_account", callback);
  }

  removeOnCreateAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.offReducer("create_account", callback);
  }

  upsertAccount(provider: string, providerUserId: string, displayName: string | undefined) {
    const __args = { provider, providerUserId, displayName };
    let __writer = new __BinaryWriter(1024);
    UpsertAccount.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("upsert_account", __argsBuffer, this.setCallReducerFlags.upsertAccountFlags);
  }

  onUpsertAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.onReducer("upsert_account", callback);
  }

  removeOnUpsertAccount(callback: (ctx: ReducerEventContext, provider: string, providerUserId: string, displayName: string | undefined) => void) {
    this.connection.offReducer("upsert_account", callback);
  }

  createOrUpdateSession(providerUserId: string, sessionToken: string, ttlMinutes: number) {
    const __args = { providerUserId, sessionToken, ttlMinutes };
    let __writer = new __BinaryWriter(1024);
    CreateOrUpdateSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_or_update_session", __argsBuffer, this.setCallReducerFlags.createOrUpdateSessionFlags);
  }

  onCreateOrUpdateSession(callback: (ctx: ReducerEventContext, providerUserId: string, sessionToken: string, ttlMinutes: number) => void) {
    this.connection.onReducer("create_or_update_session", callback);
  }

  removeOnCreateOrUpdateSession(callback: (ctx: ReducerEventContext, providerUserId: string, sessionToken: string, ttlMinutes: number) => void) {
    this.connection.offReducer("create_or_update_session", callback);
  }

  touchSession(sessionToken: string) {
    const __args = { sessionToken };
    let __writer = new __BinaryWriter(1024);
    TouchSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("touch_session", __argsBuffer, this.setCallReducerFlags.touchSessionFlags);
  }

  onTouchSession(callback: (ctx: ReducerEventContext, sessionToken: string) => void) {
    this.connection.onReducer("touch_session", callback);
  }

  removeOnTouchSession(callback: (ctx: ReducerEventContext, sessionToken: string) => void) {
    this.connection.offReducer("touch_session", callback);
  }

  createCharacter(name: string, description: string | undefined, race: string | undefined, archetype: string | undefined, profession: string | undefined, startingRegion: string | undefined) {
    const __args = { name, description, race, archetype, profession, startingRegion };
    let __writer = new __BinaryWriter(1024);
    CreateCharacter.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_character", __argsBuffer, this.setCallReducerFlags.createCharacterFlags);
  }

  onCreateCharacter(callback: (ctx: ReducerEventContext, name: string, description: string | undefined, race: string | undefined, archetype: string | undefined, profession: string | undefined, startingRegion: string | undefined) => void) {
    this.connection.onReducer("create_character", callback);
  }

  removeOnCreateCharacter(callback: (ctx: ReducerEventContext, name: string, description: string | undefined, race: string | undefined, archetype: string | undefined, profession: string | undefined, startingRegion: string | undefined) => void) {
    this.connection.offReducer("create_character", callback);
  }

  updateCharacter(id: string, patch: UpdatePatch) {
    const __args = { id, patch };
    let __writer = new __BinaryWriter(1024);
    UpdateCharacter.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_character", __argsBuffer, this.setCallReducerFlags.updateCharacterFlags);
  }

  onUpdateCharacter(callback: (ctx: ReducerEventContext, id: string, patch: UpdatePatch) => void) {
    this.connection.onReducer("update_character", callback);
  }

  removeOnUpdateCharacter(callback: (ctx: ReducerEventContext, id: string, patch: UpdatePatch) => void) {
    this.connection.offReducer("update_character", callback);
  }

  deleteCharacter(id: string) {
    const __args = { id };
    let __writer = new __BinaryWriter(1024);
    DeleteCharacter.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_character", __argsBuffer, this.setCallReducerFlags.deleteCharacterFlags);
  }

  onDeleteCharacter(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.onReducer("delete_character", callback);
  }

  removeOnDeleteCharacter(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.offReducer("delete_character", callback);
  }

  setActiveCharacter(id: string) {
    const __args = { id };
    let __writer = new __BinaryWriter(1024);
    SetActiveCharacter.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_active_character", __argsBuffer, this.setCallReducerFlags.setActiveCharacterFlags);
  }

  onSetActiveCharacter(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.onReducer("set_active_character", callback);
  }

  removeOnSetActiveCharacter(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.offReducer("set_active_character", callback);
  }

  saveCharacterDraft(id: string | undefined, draftJson: string) {
    const __args = { id, draftJson };
    let __writer = new __BinaryWriter(1024);
    SaveCharacterDraft.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("save_character_draft", __argsBuffer, this.setCallReducerFlags.saveCharacterDraftFlags);
  }

  onSaveCharacterDraft(callback: (ctx: ReducerEventContext, id: string | undefined, draftJson: string) => void) {
    this.connection.onReducer("save_character_draft", callback);
  }

  removeOnSaveCharacterDraft(callback: (ctx: ReducerEventContext, id: string | undefined, draftJson: string) => void) {
    this.connection.offReducer("save_character_draft", callback);
  }

  deleteCharacterDraft(id: string) {
    const __args = { id };
    let __writer = new __BinaryWriter(1024);
    DeleteCharacterDraft.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_character_draft", __argsBuffer, this.setCallReducerFlags.deleteCharacterDraftFlags);
  }

  onDeleteCharacterDraft(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.onReducer("delete_character_draft", callback);
  }

  removeOnDeleteCharacterDraft(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.offReducer("delete_character_draft", callback);
  }

  finalizeCharacterDraft(id: string) {
    const __args = { id };
    let __writer = new __BinaryWriter(1024);
    FinalizeCharacterDraft.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("finalize_character_draft", __argsBuffer, this.setCallReducerFlags.finalizeCharacterDraftFlags);
  }

  onFinalizeCharacterDraft(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.onReducer("finalize_character_draft", callback);
  }

  removeOnFinalizeCharacterDraft(callback: (ctx: ReducerEventContext, id: string) => void) {
    this.connection.offReducer("finalize_character_draft", callback);
  }

}

export class SetReducerFlags {
  createAccountFlags: __CallReducerFlags = 'FullUpdate';
  createAccount(flags: __CallReducerFlags) {
    this.createAccountFlags = flags;
  }

  upsertAccountFlags: __CallReducerFlags = 'FullUpdate';
  upsertAccount(flags: __CallReducerFlags) {
    this.upsertAccountFlags = flags;
  }

  createOrUpdateSessionFlags: __CallReducerFlags = 'FullUpdate';
  createOrUpdateSession(flags: __CallReducerFlags) {
    this.createOrUpdateSessionFlags = flags;
  }

  touchSessionFlags: __CallReducerFlags = 'FullUpdate';
  touchSession(flags: __CallReducerFlags) {
    this.touchSessionFlags = flags;
  }

  createCharacterFlags: __CallReducerFlags = 'FullUpdate';
  createCharacter(flags: __CallReducerFlags) {
    this.createCharacterFlags = flags;
  }

  updateCharacterFlags: __CallReducerFlags = 'FullUpdate';
  updateCharacter(flags: __CallReducerFlags) {
    this.updateCharacterFlags = flags;
  }

  deleteCharacterFlags: __CallReducerFlags = 'FullUpdate';
  deleteCharacter(flags: __CallReducerFlags) {
    this.deleteCharacterFlags = flags;
  }

  setActiveCharacterFlags: __CallReducerFlags = 'FullUpdate';
  setActiveCharacter(flags: __CallReducerFlags) {
    this.setActiveCharacterFlags = flags;
  }

  saveCharacterDraftFlags: __CallReducerFlags = 'FullUpdate';
  saveCharacterDraft(flags: __CallReducerFlags) {
    this.saveCharacterDraftFlags = flags;
  }

  deleteCharacterDraftFlags: __CallReducerFlags = 'FullUpdate';
  deleteCharacterDraft(flags: __CallReducerFlags) {
    this.deleteCharacterDraftFlags = flags;
  }

  finalizeCharacterDraftFlags: __CallReducerFlags = 'FullUpdate';
  finalizeCharacterDraft(flags: __CallReducerFlags) {
    this.finalizeCharacterDraftFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get accounts(): AccountsTableHandle<'accounts'> {
    // clientCache is a private property
    return new AccountsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Accounts>(REMOTE_MODULE.tables.accounts));
  }

  get characterDrafts(): CharacterDraftsTableHandle<'character_drafts'> {
    // clientCache is a private property
    return new CharacterDraftsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<CharacterDrafts>(REMOTE_MODULE.tables.character_drafts));
  }

  get characters(): CharactersTableHandle<'characters'> {
    // clientCache is a private property
    return new CharactersTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Characters>(REMOTE_MODULE.tables.characters));
  }

  get sessions(): SessionsTableHandle<'sessions'> {
    // clientCache is a private property
    return new SessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Sessions>(REMOTE_MODULE.tables.sessions));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
