// SpaceTimeDB accounts module stub
// In real implementation this file would be generated by SpaceTimeDB tooling.
import { Account } from '../../shared-schema/src/index.ts';
import { randomUUID } from 'crypto';

export async function upsertAccount(provider: string, providerUserId: string, displayName: string): Promise<Account> {
    const now = Date.now();
    return {
        id: randomUUID(),
        provider: provider as any,
        providerUserId,
        displayName,
        createdAt: now,
        updatedAt: now
    };
}
