export const styles = {
  shell: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'linear-gradient(135deg, #0b0c10 0%, #141821 40%, #0d1117 100%)',
    color: '#e6e8ef',
    fontFamily: '"PT Serif", "Georgia", serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '1.5rem 2rem',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
  },
  headerRight: {
    textAlign: 'right',
  },
  authRow: {
    marginTop: '0.6rem',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '0.5rem',
  },
  authForm: {
    display: 'flex',
    gap: '0.5rem',
  },
  authLoggedIn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
  },
  authEmail: {
    color: 'rgba(230,232,239,0.8)',
    fontSize: '0.8rem',
  },
  authInput: {
    background: '#0b0f16',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#e6e8ef',
    padding: '0.35rem 0.6rem',
    borderRadius: '8px',
  },
  authMessage: {
    color: 'rgba(124, 242, 154, 0.85)',
    fontSize: '0.75rem',
  },
  authError: {
    color: 'rgba(255, 125, 125, 0.85)',
    fontSize: '0.75rem',
  },
  errorText: {
    color: 'rgba(255, 125, 125, 0.85)',
    fontSize: '0.8rem',
  },
  title: {
    fontSize: '1.75rem',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  subtle: {
    color: 'rgba(230,232,239,0.65)',
    fontSize: '0.9rem',
  },
  statusOnline: {
    color: '#7cf29a',
    marginLeft: '0.4rem',
  },
  statusOffline: {
    color: '#ff7d7d',
    marginLeft: '0.4rem',
  },
  main: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: '1fr minmax(260px, 320px)',
    gap: '1.5rem',
    padding: '1.5rem 2rem',
    minHeight: 0,
    overflow: 'hidden',
  },
  mainWide: {
    gridTemplateColumns: '1fr',
  },
  log: {
    background: 'rgba(12, 15, 22, 0.75)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '14px',
    padding: '1.5rem',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
  },
  logOverlay: {
    position: 'relative',
    height: '100%',
    minHeight: 0,
  },
  logOverlayPanel: {
    position: 'absolute',
    top: '1rem',
    right: '1rem',
    width: 'min(320px, 90%)',
    maxHeight: 'calc(100% - 2rem)',
    overflow: 'auto',
    background: '#141821',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '14px',
    padding: '1rem',
    boxShadow: '0 12px 30px rgba(0,0,0,0.45)',
    zIndex: 5,
  },
  roster: {
    marginBottom: '1rem',
    padding: '0.75rem 0.9rem',
    borderRadius: '10px',
    background: 'rgba(16, 20, 28, 0.65)',
    border: '1px solid rgba(255,255,255,0.08)',
  },
  rosterTitle: {
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    fontSize: '0.7rem',
    marginBottom: '0.5rem',
    color: 'rgba(230,232,239,0.6)',
  },
  rosterList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.4rem',
  },
  rosterTag: {
    background: 'rgba(76, 125, 240, 0.2)',
    border: '1px solid rgba(76, 125, 240, 0.5)',
    padding: '0.25rem 0.6rem',
    borderRadius: '999px',
    fontSize: '0.8rem',
  },
  logList: {
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.6rem',
    flex: 1,
    paddingRight: '0.5rem',
  },
  logItem: {
    display: 'flex',
    gap: '0.5rem',
    fontFamily: '"Source Code Pro", "Consolas", monospace',
    fontSize: '0.95rem',
  },
  logTime: {
    color: 'rgba(230,232,239,0.5)',
    minWidth: '72px',
  },
  logKind: {
    color: '#8bd3ff',
    textTransform: 'uppercase',
    fontSize: '0.75rem',
    letterSpacing: '0.12em',
    marginTop: '0.15rem',
  },
  logText: {
    flex: 1,
  },
  logPrivate: {
    color: 'rgba(230, 232, 239, 0.85)',
  },
  logPresence: {
    color: 'rgba(230, 232, 239, 0.55)',
  },
  logCommand: {
    color: '#e0b565',
  },
  logWhisper: {
    color: '#c792ff',
  },
  logEmpty: {
    color: 'rgba(230,232,239,0.6)',
    fontStyle: 'italic',
  },
  panel: {
    background: 'rgba(20,24,33,0.85)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '14px',
    padding: '1rem',
    minHeight: '320px',
    display: 'flex',
    flexDirection: 'column',
  },
  panelStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    minHeight: 0,
  },
  panelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontSize: '0.8rem',
  },
  panelClose: {
    background: 'transparent',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#e6e8ef',
    padding: '0.3rem 0.6rem',
    borderRadius: '999px',
    cursor: 'pointer',
  },
  panelBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  panelSectionTitle: {
    fontSize: '0.85rem',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: 'rgba(230,232,239,0.7)',
  },
  combatTimer: {
    fontFamily: '"Source Code Pro", "Consolas", monospace',
    fontSize: '1rem',
    color: '#f6d365',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  hpBar: {
    height: '8px',
    borderRadius: '999px',
    background: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
    marginTop: '0.25rem',
  },
  hpFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #6bdc8c 0%, #38b2ac 100%)',
  },
  manaFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #5da0ff 0%, #3b6ea5 100%)',
  },
  staminaFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #f6d365 0%, #fda085 100%)',
  },
  panelForm: {
    display: 'grid',
    gap: '0.5rem',
  },
  panelFormInline: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
  },
  input: {
    background: '#0b0f16',
    border: '1px solid rgba(255,255,255,0.15)',
    color: '#e6e8ef',
    padding: '0.5rem 0.6rem',
    borderRadius: '8px',
  },
  smallInput: {
    background: '#0b0f16',
    border: '1px solid rgba(255,255,255,0.15)',
    color: '#e6e8ef',
    padding: '0.4rem 0.6rem',
    borderRadius: '8px',
    width: '90px',
  },
  list: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  radioRow: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
  },
  checkboxRow: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
    fontSize: '0.85rem',
    color: 'rgba(230,232,239,0.75)',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.5rem 1rem',
    fontSize: '0.95rem',
  },
  buttonWrap: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  primaryButton: {
    background: '#4c7df0',
    border: 'none',
    color: '#0b0f16',
    padding: '0.5rem 0.9rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  actionButtonSelected: {
    background: '#4c7df0',
    border: '1px solid #4c7df0',
    color: '#0b0f16',
    padding: '0.4rem 0.8rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  ghostButton: {
    background: 'transparent',
    border: '1px solid rgba(255,255,255,0.25)',
    color: '#e6e8ef',
    padding: '0.4rem 0.8rem',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  footer: {
    padding: '1rem 2rem 1.5rem',
    borderTop: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(8,10,15,0.9)',
  },
  commandBar: {
    display: 'flex',
    gap: '0.75rem',
    marginBottom: '0.75rem',
    width: '100%',
    alignItems: 'stretch',
  },
  commandWrapper: {
    position: 'relative',
    flex: 1,
    minWidth: 0,
  },
  commandInput: {
    width: '100%',
    background: '#0b0f16',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#e6e8ef',
    padding: '0.7rem 0.8rem',
    borderRadius: '10px',
    fontFamily: '"Source Code Pro", "Consolas", monospace',
    boxSizing: 'border-box',
  },
  commandSuggestions: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 'calc(100% + 0.5rem)',
    background: 'rgba(9, 12, 18, 0.98)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '10px',
    padding: '0.4rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
    zIndex: 20,
  },
  commandSuggestionItem: {
    background: 'transparent',
    border: '1px solid transparent',
    color: '#e6e8ef',
    textAlign: 'left',
    padding: '0.4rem 0.6rem',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    gap: '0.75rem',
    fontFamily: '"Source Code Pro", "Consolas", monospace',
    fontSize: '0.85rem',
  },
  commandSuggestionItemActive: {
    background: 'rgba(76, 125, 240, 0.2)',
    border: '1px solid rgba(76, 125, 240, 0.5)',
  },
  commandSuggestionHint: {
    color: 'rgba(230,232,239,0.55)',
    fontSize: '0.75rem',
  },
  actionBar: {
    display: 'flex',
    gap: '0.6rem',
    flexWrap: 'wrap',
  },
  actionButton: {
    background: 'transparent',
    border: '1px solid rgba(255,255,255,0.2)',
    color: '#e6e8ef',
    padding: '0.45rem 0.9rem',
    borderRadius: '999px',
    cursor: 'pointer',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    fontSize: '0.75rem',
  },
  actionButtonActive: {
    background: '#4c7df0',
    color: '#0b0f16',
    border: '1px solid #4c7df0',
  },
} as const;
