// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CallLlmProcedure from "../call_llm_procedure";

export type CallLlmArgs = __Infer<typeof CallLlmProcedure.params>;
export type CallLlmResult = __Infer<typeof CallLlmProcedure.returnType>;

