export type ViewDeps = {
  spacetimedb: any;
  t: any;
  Player: any;
  FriendRequest: any;
  Friend: any;
  GroupInvite: any;
  EventGroup: any;
  GroupMember: any;
  CharacterEffect: any;
  CombatResult: any;
  CombatLoot: any;
  EventLocation: any;
  EventPrivate: any;
  NpcDialog: any;
  QuestInstance: any;
  Hunger: any;
  Faction: any;
  FactionStanding: any;
  UiPanelLayout: any;
};
