// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerId: __t.identity().name("player_id"),
  step: __t.string(),
  goBackTarget: __t.option(__t.string()).name("go_back_target"),
  raceDescription: __t.option(__t.string()).name("race_description"),
  raceName: __t.option(__t.string()).name("race_name"),
  raceNarrative: __t.option(__t.string()).name("race_narrative"),
  raceBonuses: __t.option(__t.string()).name("race_bonuses"),
  archetype: __t.option(__t.string()),
  className: __t.option(__t.string()).name("class_name"),
  classDescription: __t.option(__t.string()).name("class_description"),
  classStats: __t.option(__t.string()).name("class_stats"),
  abilities: __t.option(__t.string()),
  chosenAbilityIndex: __t.option(__t.u64()).name("chosen_ability_index"),
  characterName: __t.option(__t.string()).name("character_name"),
  previousStep: __t.option(__t.string()).name("previous_step"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
