// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64().name("combat_id"),
  roundNumber: __t.u64().name("round_number"),
  narrativeText: __t.string().name("narrative_text"),
  narrativeType: __t.string().name("narrative_type"),
  createdAt: __t.timestamp().name("created_at"),
});
