// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64().name("combat_id"),
  characterId: __t.u64().name("character_id"),
  roundNumber: __t.u64().name("round_number"),
  actionType: __t.string().name("action_type"),
  abilityTemplateId: __t.option(__t.u64()).name("ability_template_id"),
  targetEnemyId: __t.option(__t.u64()).name("target_enemy_id"),
  targetCharacterId: __t.option(__t.u64()).name("target_character_id"),
  submittedAt: __t.timestamp().name("submitted_at"),
});
