// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  combatId: __t.u64().name("combat_id"),
  spawnId: __t.u64().name("spawn_id"),
  enemyTemplateId: __t.u64().name("enemy_template_id"),
  enemyRoleTemplateId: __t.option(__t.u64()).name("enemy_role_template_id"),
  displayName: __t.string().name("display_name"),
  currentHp: __t.u64().name("current_hp"),
  maxHp: __t.u64().name("max_hp"),
  attackDamage: __t.u64().name("attack_damage"),
  armorClass: __t.u64().name("armor_class"),
  aggroTargetCharacterId: __t.option(__t.u64()).name("aggro_target_character_id"),
  aggroTargetPetId: __t.option(__t.u64()).name("aggro_target_pet_id"),
  nextAutoAttackAt: __t.u64().name("next_auto_attack_at"),
});
