// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  role: __t.string(),
  roleDetail: __t.string().name("role_detail"),
  abilityProfile: __t.string().name("ability_profile"),
  terrainTypes: __t.string().name("terrain_types"),
  creatureType: __t.string().name("creature_type"),
  timeOfDay: __t.string().name("time_of_day"),
  socialGroup: __t.string().name("social_group"),
  socialRadius: __t.u64().name("social_radius"),
  awareness: __t.string(),
  groupMin: __t.u64().name("group_min"),
  groupMax: __t.u64().name("group_max"),
  armorClass: __t.u64().name("armor_class"),
  level: __t.u64(),
  maxHp: __t.u64().name("max_hp"),
  baseDamage: __t.u64().name("base_damage"),
  xpReward: __t.u64().name("xp_reward"),
  factionId: __t.option(__t.u64()).name("faction_id"),
  isBoss: __t.option(__t.bool()).name("is_boss"),
  isSocial: __t.option(__t.bool()).name("is_social"),
  bossRegionName: __t.option(__t.string()).name("boss_region_name"),
});
