// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  locationId: __t.u64().name("location_id"),
  enemyTemplateId: __t.u64().name("enemy_template_id"),
  name: __t.string(),
  state: __t.string(),
  lockedCombatId: __t.option(__t.u64()).name("locked_combat_id"),
  groupCount: __t.u64().name("group_count"),
});
