// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  enemyTemplateId: __t.u64().name("enemy_template_id"),
  abilityKey: __t.string().name("ability_key"),
  name: __t.string(),
  kind: __t.string(),
  castSeconds: __t.u64().name("cast_seconds"),
  cooldownSeconds: __t.u64().name("cooldown_seconds"),
  targetRule: __t.string().name("target_rule"),
});
