// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventId: __t.u64().name("event_id"),
  objectiveType: __t.string().name("objective_type"),
  locationId: __t.u64().name("location_id"),
  name: __t.string(),
  targetCount: __t.u64().name("target_count"),
  currentCount: __t.u64().name("current_count"),
  isAlive: __t.option(__t.bool()).name("is_alive"),
});
