// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  slot: __t.string(),
  armorType: __t.string().name("armor_type"),
  rarity: __t.string(),
  tier: __t.u64(),
  isJunk: __t.bool().name("is_junk"),
  vendorValue: __t.u64().name("vendor_value"),
  requiredLevel: __t.u64().name("required_level"),
  allowedClasses: __t.string().name("allowed_classes"),
  strBonus: __t.u64().name("str_bonus"),
  dexBonus: __t.u64().name("dex_bonus"),
  chaBonus: __t.u64().name("cha_bonus"),
  wisBonus: __t.u64().name("wis_bonus"),
  intBonus: __t.u64().name("int_bonus"),
  hpBonus: __t.u64().name("hp_bonus"),
  manaBonus: __t.u64().name("mana_bonus"),
  armorClassBonus: __t.u64().name("armor_class_bonus"),
  magicResistanceBonus: __t.u64().name("magic_resistance_bonus"),
  weaponBaseDamage: __t.u64().name("weapon_base_damage"),
  weaponDps: __t.u64().name("weapon_dps"),
  weaponType: __t.string().name("weapon_type"),
  stackable: __t.bool(),
  wellFedDurationMicros: __t.u64().name("well_fed_duration_micros"),
  wellFedBuffType: __t.string().name("well_fed_buff_type"),
  wellFedBuffMagnitude: __t.u64().name("well_fed_buff_magnitude"),
  description: __t.option(__t.string()),
});
