// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  templateId: __t.u64(),
  ownerCharacterId: __t.u64(),
  equippedSlot: __t.option(__t.string()),
  quantity: __t.u64(),
  qualityTier: __t.option(__t.string()),
  craftQuality: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  isNamed: __t.option(__t.bool()),
  isTemporary: __t.option(__t.bool()),
});
