// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("ItemAffix", {
  id: __t.u64(),
  itemInstanceId: __t.u64(),
  affixType: __t.string(),
  affixKey: __t.string(),
  affixName: __t.string(),
  statKey: __t.string(),
  magnitude: __t.i64(),
});


