// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  name: __t.string(),
  enemyTemplateId: __t.u64().name("enemy_template_id"),
  locationId: __t.u64().name("location_id"),
  isAlive: __t.bool().name("is_alive"),
  lastKilledAt: __t.option(__t.timestamp()).name("last_killed_at"),
  respawnMinutes: __t.u64().name("respawn_minutes"),
});
