// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  npcId: __t.u64().name("npc_id"),
  parentOptionId: __t.option(__t.u64()).name("parent_option_id"),
  optionKey: __t.string().name("option_key"),
  playerText: __t.string().name("player_text"),
  npcResponse: __t.string().name("npc_response"),
  requiredAffinity: __t.i64().name("required_affinity"),
  requiredFactionId: __t.option(__t.u64()).name("required_faction_id"),
  requiredFactionStanding: __t.option(__t.i64()).name("required_faction_standing"),
  requiredRenownRank: __t.option(__t.u64()).name("required_renown_rank"),
  affinityChange: __t.i64().name("affinity_change"),
  sortOrder: __t.u64().name("sort_order"),
  questTemplateName: __t.option(__t.string()).name("quest_template_name"),
  affinityHint: __t.option(__t.string()).name("affinity_hint"),
  isAffinityLocked: __t.option(__t.bool()).name("is_affinity_locked"),
});
