// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  npcId: __t.u64(),
  parentOptionId: __t.option(__t.u64()),
  optionKey: __t.string(),
  playerText: __t.string(),
  npcResponse: __t.string(),
  requiredAffinity: __t.i64(),
  requiredFactionId: __t.option(__t.u64()),
  requiredFactionStanding: __t.option(__t.i64()),
  requiredRenownRank: __t.option(__t.u64()),
  affinityChange: __t.i64(),
  sortOrder: __t.u64(),
  questTemplateName: __t.option(__t.string()),
  affinityHint: __t.option(__t.string()),
  isAffinityLocked: __t.option(__t.bool()),
});
