// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  npcId: __t.u64().name("npc_id"),
  affinity: __t.i64(),
  lastInteraction: __t.timestamp().name("last_interaction"),
  giftsGiven: __t.u64().name("gifts_given"),
  conversationCount: __t.u64().name("conversation_count"),
  hasGreeted: __t.option(__t.bool()).name("has_greeted"),
});
