// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  spellType: __t.string().name("spell_type"),
  casterCharacterId: __t.u64().name("caster_character_id"),
  targetCharacterId: __t.u64().name("target_character_id"),
  corpseId: __t.option(__t.u64()).name("corpse_id"),
  createdAtMicros: __t.u64().name("created_at_micros"),
});
