// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64().name("character_id"),
  groupId: __t.option(__t.u64()).name("group_id"),
  locationId: __t.u64().name("location_id"),
  enemySpawnId: __t.u64().name("enemy_spawn_id"),
  pullType: __t.string().name("pull_type"),
  state: __t.string(),
  outcome: __t.option(__t.string()),
  delayedAdds: __t.option(__t.u64()).name("delayed_adds"),
  delayedAddsAtMicros: __t.option(__t.u64()).name("delayed_adds_at_micros"),
  createdAt: __t.timestamp().name("created_at"),
});
