// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  characterId: __t.u64(),
  groupId: __t.option(__t.u64()),
  locationId: __t.u64(),
  enemySpawnId: __t.u64(),
  pullType: __t.string(),
  state: __t.string(),
  outcome: __t.option(__t.string()),
  delayedAdds: __t.option(__t.u64()),
  delayedAddsAtMicros: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
