// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  availableClasses: __t.string().name("available_classes"),
  bonus1Type: __t.string().name("bonus_1_type"),
  bonus1Value: __t.u64().name("bonus_1_value"),
  bonus2Type: __t.string().name("bonus_2_type"),
  bonus2Value: __t.u64().name("bonus_2_value"),
  penaltyType: __t.option(__t.string()).name("penalty_type"),
  penaltyValue: __t.option(__t.u64()).name("penalty_value"),
  levelBonusType: __t.string().name("level_bonus_type"),
  levelBonusValue: __t.u64().name("level_bonus_value"),
  unlocked: __t.bool(),
});
