// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  name: __t.string(),
  outputTemplateId: __t.u64().name("output_template_id"),
  outputCount: __t.u64().name("output_count"),
  req1TemplateId: __t.u64().name("req_1_template_id"),
  req1Count: __t.u64().name("req_1_count"),
  req2TemplateId: __t.u64().name("req_2_template_id"),
  req2Count: __t.u64().name("req_2_count"),
  req3TemplateId: __t.option(__t.u64()).name("req_3_template_id"),
  req3Count: __t.option(__t.u64()).name("req_3_count"),
  recipeType: __t.option(__t.string()).name("recipe_type"),
  materialType: __t.option(__t.string()).name("material_type"),
});
