// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  dangerMultiplier: __t.u64().name("danger_multiplier"),
  regionType: __t.string().name("region_type"),
  biome: __t.option(__t.string()),
  dominantFaction: __t.option(__t.string()).name("dominant_faction"),
  landmarks: __t.option(__t.string()),
  threats: __t.option(__t.string()),
  generatedByCharacterId: __t.option(__t.u64()).name("generated_by_character_id"),
  isGenerated: __t.option(__t.bool()).name("is_generated"),
});
