// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  fromCharacterId: __t.u64().name("from_character_id"),
  toCharacterId: __t.u64().name("to_character_id"),
  state: __t.string(),
  fromAccepted: __t.bool().name("from_accepted"),
  toAccepted: __t.bool().name("to_accepted"),
  createdAt: __t.timestamp().name("created_at"),
});
