// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  statKey: __t.string().name("stat_key"),
  currentValue: __t.u64().name("current_value"),
  fireThreshold: __t.u64().name("fire_threshold"),
  eventKeyToFire: __t.string().name("event_key_to_fire"),
  fired: __t.bool(),
});
