// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Characters = {
  id: string,
  ownerId: string,
  name: string,
  description: string | undefined,
  race: string | undefined,
  archetype: string | undefined,
  profession: string | undefined,
  startingRegion: string | undefined,
  createdAt: __Timestamp,
  currentLocation: string | undefined,
  strength: number | undefined,
  dexterity: number | undefined,
  intelligence: number | undefined,
  constitution: number | undefined,
  wisdom: number | undefined,
  charisma: number | undefined,
  maxHealth: number | undefined,
  currentHealth: number | undefined,
  maxMana: number | undefined,
  currentMana: number | undefined,
  raceAbilities: string | undefined,
  professionAbilities: string | undefined,
  armorType: string | undefined,
  level: number | undefined,
  xp: number | undefined,
  inventoryItems: string | undefined,
  backpack: string | undefined,
  head: string | undefined,
  shoulders: string | undefined,
  back: string | undefined,
  chest: string | undefined,
  arms: string | undefined,
  hands: string | undefined,
  legs: string | undefined,
  feet: string | undefined,
  rings: string | undefined,
  necklace: string | undefined,
  earrings: string | undefined,
  relic: string | undefined,
  primaryWeapon: string | undefined,
  secondaryWeapon: string | undefined,
  quests: string | undefined,
};
let _cached_Characters_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Characters = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Characters_type_value) return _cached_Characters_type_value;
    _cached_Characters_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Characters_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.String },
      { name: "ownerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "name", algebraicType: __AlgebraicTypeValue.String },
      { name: "description", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "race", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "archetype", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "profession", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "startingRegion", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType() },
      { name: "currentLocation", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "strength", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "dexterity", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "intelligence", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "constitution", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "wisdom", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "charisma", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "maxHealth", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "currentHealth", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "maxMana", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "currentMana", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "raceAbilities", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "professionAbilities", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "armorType", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "level", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "xp", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32) },
      { name: "inventoryItems", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "backpack", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "head", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "shoulders", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "back", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "chest", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "arms", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "hands", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "legs", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "feet", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "rings", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "necklace", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "earrings", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "relic", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "primaryWeapon", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "secondaryWeapon", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
      { name: "quests", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
    );
    return _cached_Characters_type_value;
  },

  serialize(writer: __BinaryWriter, value: Characters): void {
    __AlgebraicTypeValue.serializeValue(writer, Characters.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Characters {
    return __AlgebraicTypeValue.deserializeValue(reader, Characters.getTypeScriptAlgebraicType());
  },

}

export default Characters;


